### ISSUE TITLE
DC kicks you from battlegrounds

### ISSUE THREAD

**Issue by afizzler** [slowtorta/turtlewow-bug-tracker#1169]
The bug occurs when you disconnect from the game while in a battleground due to internet. It kicks you from the battleground and gives you a deserter.

1. Join a battleground like WSG/AB/AV
2. Disconnect yourself from the internet
3. Reconnect yourself to the internet
4. Relog into the game

Disconnecting should keep you in the battleground because your character does not fully go offline after a certain amount of time from the disconnect.

**Comment by slowtorta** [comment]
Sorry, but this is working as intended. Can't have offline players on the Battleground.

**Comment by burner1024** [comment]
This makes no sense. There's an afk timer, kick by timer. A momentary DC does not equal offline player.

**Comment by Zebouski** [comment]
Torta please elaborate what you mean by "can't have offline players". Is it a technical issue that literally cannot be done with this client?

Or a design you are sticking to? Because if its the later, blizz Classic has a 2 minute grace period where if you DC, and reconnect in that timeframe, you are back in the BG and get to keep playing + no deserter. This is universally loved and isn't abusable.

Deserter is a giant middle finger towards a player who did nothing wrong themselves (IE turtle wow had a bug or their internet just had a moment).

Please reconsider, this is a MASSIVE issue.
