### ISSUE TITLE
 items with no character lv  requirement

### ISSUE THREAD

**Issue by salibardo** [slowtorta/turtlewow-bug-tracker#1318]
**Please, provide a clear description what the bug is: item character level requirement i saw that there are few items that turtle wow added that have no level requirement and because of it there are a pathologic characters with very high item level and very low character level

**Steps to reproduce the behavior with as much detail as possible:**

1.i saw a few people on low level that have over 1000 hp o lv 10 that are kiling other a low level players who have no chance againt them
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=5355
https://database.turtle-wow.org/?item=10781
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:** you should check items that turtle wow added and give them level requirement corresponding with their item lv

**Comment by slowtorta** [comment]
Item: https://database.turtle-wow.org/?item=5355 isn't bugged, it's an intended Vanilla behavior.
Item: https://database.turtle-wow.org/?item=10781 isn't bugged as well, however it shouldn't drop for this mob with such a high chance. It'll be fixed in the next revision: https://database.turtle-wow.org/?item=10781
