### ISSUE TITLE
Rejold's New Brew Quest

### ISSUE THREAD

**Issue by Doomfist12** [slowtorta/turtlewow-bug-tracker#1490]
Tharek Blakstone and/or Pilot Bellowfiz are supposed to give out the quest ''Rejold's New Brew'' after the completion of ''The Perfect Stout''. They however, currently don't do this.

[Tharek Blackstone](https://database.turtle-wow.org/?npc=1872)
https://database.turtle-wow.org/?quest=415
https://database.turtle-wow.org/?quest=413

**Expected behavior. Describe how it should work:**
This quest should opens after the completion of ''The Perfect Stout'' and closes if you have already completed  the quest ''Shimmer Stout''. I however haven't completed that quest [Shimmer Stout], but it's still not given by the NPC.

**Comment by slowtorta** [comment]
Fixed in the next revision.

**Comment by JoLiKMC** [comment]
I just want to point something out: this quest **is not broken**.  The problem lies in the quest order.

Completing the quest "[The Perfect Stout](https://database.turtle-wow.org/?quest=315)" automatically unlocks "Shimmer Stout" if the player is Level 8 or higher.  Accepting "Shimmer Stout" automatically nullifies "Rejold's New Brew".

Presently, if players want to do both quests, they need to _ignore_ "Shimmer Stout", then go talk to [Tharek Blackstone](https://database.turtle-wow.org/?npc=1872) in Kharanos.  They can grab "Rejold's New Brew" and be funneled back toward Rejold, then.

It's also worth mentioning that Pilot Bellowfiz was never intended to give out this quest.  This is simply an error in the _Turtle WoW_ pfQuest database module.
