### ISSUE TITLE
Harken Windtotem has empty faction ("You are now Friendly with .")

### ISSUE THREAD

**Issue by 9600bauds** [slowtorta/turtlewow-bug-tracker#1576]
**Steps to reproduce the behavior with as much detail as possible:**

1. Make new character
2. Talk to Harken Windtotem
3. You are now friendly with .

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2947

**Expected behavior. Describe how it should work:**
His faction should be "Thunder Bluff" like other nearby NPCs: https://database.turtle-wow.org/?npc=3066

**Comment by JoLiKMC** [comment]
That's intentional.  There are a handful of NPCs with the faction of " ".  There are two such factions, in fact – one on the Alliance side and one on the Horde side.  Honestly, it wouldn't hurt anything if the factions were renamed "Horde / Alliance Forces" or something.

Hilariously, you can actually _go to war_ with the one on your faction's side and _kill_ any NPCs with that faction.  Every time I'm in Thunder Bluff, I make sure to kill Harken Windtotem.  Hee hee.

**Comment by 9600bauds** [comment]
Out of curiosity, what is the purpose of this ghost faction?

**Comment by slowtorta** [comment]
Fixed in the next client patch.
