### ISSUE TITLE
I get Net-o-Matic debuff if I log into the game

### ISSUE THREAD

**Issue by Shellyoung** [slowtorta/turtlewow-bug-tracker#1583]
**Please, provide a clear description what the bug is:**
I get Net-o-Matic debuff if I log into the game. It happens every time when I log in. Video: [https://i.imgur.com/5ZhvYkz.gif](https://i.imgur.com/5ZhvYkz.gif)

**Steps to reproduce the behavior with as much detail as possible:**
1. May be log into the game using my character?

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=10720 (I have this item in my bag)
Spell: https://database.turtle-wow.org/?spell=13138 (I may be wrong, but it has 20 seconds duration time like the debuff I talk about)

**Expected behavior. Describe how it should work:**
I should not get Net-o-Matic debuff if I log into WoW.

**Comment by Shellyoung** [comment]
The bug do not happen anymore.

**Comment by Iacov** [comment]
@slowtorta please re-open this is a persisting issue :

https://database.turtle-wow.org/?spell=13138 is making checks upon login as if the item was equipped, this after using https://database.turtle-wow.org/?item=10720 in one session, then logging out even hours/days after will trigger:

https://database.turtle-wow.org/?spell=13139
or
https://database.turtle-wow.org/?spell=16566
The two malfunctions.

Ironically, this can be game-breaking like for myself relogging on fpath and net dropping me off it getting me stuck in a loop because CC on mounted flight path renders unusable (to avoid abuse, i'm aware):

![image](https://user-images.githubusercontent.com/6597238/190623007-d2d7c966-6a0f-4a00-93dc-28a7bfea7237.png)

so now i'm stuck in a loop, unable to dismount, can't even [Auto-Unstuck] as it cannot be used mounted:

![image](https://user-images.githubusercontent.com/6597238/190623400-ba5d7e09-eae2-4a24-80e8-e085ce278a31.png)

Please look into this,

Thank you,
