### ISSUE TITLE
torturing poker only does physical damage

### ISSUE THREAD

**Issue by burner1024** [slowtorta/turtlewow-bug-tracker#1685]
**Please, provide a clear description what the bug is:**
Torturing Poker should do physical/fire damage combo. Instead, all damage seems to be physical.
Fire damage is mitigated by resists, physical by armor.
![Captura de pantalla de 2022-07-27 18-25-13](https://user-images.githubusercontent.com/1279852/181236032-f28ffb0d-9760-4d74-8233-f0fc8072d453.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Equip poker.
2. Hit training dummy.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Db down.

**Expected behavior. Describe how it should work:**
Fire damage component should bypass armor, should be possible to resist.

(Probably same goes for [Thornfist](https://database.turtle-wow.org/?item=80750))

**Comment by redmagejoe** [comment]
This one is hard to test unless we know how exacty this damage is handled and how the Combat Log displays it. It is melee damage of the fire element, yes, rather than a separate proc of spell damage. This means it may NOT show up separately in the combat log, but still be doing fire element damage. The item would have to be run by a core dev to know if it is working properly or not.

Whatever the case, I would not expect to see a separate 5-7 fire damage instance in combat log the same way Flametongue Weapon or Seal of Righteousness works.

**Comment by burner1024** [comment]
If you want to test, should be easy with a fire protection potion.
Either way, I don't see how to display resists/absorbs if not separately.

**Comment by jameyboor** [comment]
Confirmed working.
