### ISSUE TITLE
Zeppelin Landing in Durotar from the Swamp of Sorrows Docks Incorrectly

### ISSUE THREAD

**Issue by JoLiKMC** [slowtorta/turtlewow-bug-tracker#1697]
When the zeppelin from Kargoth, Swamp of Sorrows docks in front the western zeppelin tower in front of Orgrimmar (Durotar), it stops moving a little farther back than it should, leading to a somewhat awkward boarding process.

**Steps to reproduce the behavior with as much detail as possible:**
1. Create a new orc or troll and log in
(A pre-existing character is fine, too.  Just someone who's near Orgrimmar.)
2. Climb the West Zeppelin Tower outside of Orgrimmar and wait for the northern zeppelin to Kargoth
3. Behold the wonky way it docks!

**Expected behavior. Describe how it should work:**
The opening of the zeppelin should be as close to centered on the wooden platform of the tower as possible, much like the other three zeppelins.  It should also park a tiny by closer.

**Relevant screenshots:**
![TWoW_116-1_WonkyZep](https://user-images.githubusercontent.com/102710555/181354582-9fa761da-3455-4c3d-9a18-ad4b49d390d7.jpg)
_"Hey!  You missed your mark!!  Pull forward a little, there!"_

**Comment by slowtorta** [comment]
Sorry, transport is very hard to add and I'm happy that it swims at all. Minor docking misplacement will have to stay.

**Comment by JoLiKMC** [comment]
The thing is… it wasn't doing that before Patch 1.16.1.  So, ya know…

**Comment by slowtorta** [comment]
Sadly, it was exactly the same in the previous patch: tower position didn't change, otherwise, we'd have Thunder Bluff zeppelin misplaced as well, zeppelin docking coordinates are exactly the same as they were before. This bug has one of the lowest priorities and this has to stay as it is for now. Eventually, when we have better tools for that, we might adjust it to work a bit more smoothly.
