### ISSUE TITLE
Bugged quest "Pyrewood Ambush" - Horde only

### ISSUE THREAD

**Issue by Olamek** [slowtorta/turtlewow-bug-tracker#1708]
Hello,

I found out that quest "Pyrewood Ambush" (quest giver "Deathstalker Faerleia" in Silverpine Forest) is bugged.

This quest is about beating couple of ways of elite creeps, after defeating last one, quest giver just announce that PC did a good a job but quest is not set as complete (try to do it at least 5 times, always with the same outcome).

Last time tried quest on Monday 25th.

Could you take a look at it and possible fix it?

Thanks

Best regards

**Comment by sharlatan** [comment]
UP,still not working.

**Comment by slowtorta** [comment]
Also related to https://github.com/slowtorta/turtlewow-bug-tracker/issues/1520

**Comment by Haaxor1689** [comment]
Quest still doesn't correctly give completion credit. Tested right now now on live.

**Comment by Haaxor1689** [comment]
You can pick it up again but you need to wait for the quest giver to reset

**Comment by Herdon** [comment]
I did wait for at least 10+ hours (logged out next to her and went to sleep) and when I logged back in she still didn't want to give me the quest.

**Comment by Haaxor1689** [comment]
Then I think you need to wait for the server reset but no point in trying since it's bugged.

**Comment by Herdon** [comment]
As of the time I'm writing this 22 March. After the server restart I tried the quest again and what do you know ?
![WoWScrnShot_032223_031325](https://user-images.githubusercontent.com/2021593/226784695-7ab2983d-9a9c-45f4-a0ba-dc6c5fe063e3.jpg)
Everything worked perfectly. Waves came at reasonable time. They engaged properly. NPC healed herself after each wave etc. Completed the quest without a problem. Unfortunately I don't have second character to try it again and see if it works for him too.

**Comment by Bovrilmatter** [comment]
Still having the issue of not being able to complete this quest I could imagine after a server reset it is possible as the person above has shown but right now on the server after you kill all the waves you get the message "Well done. A blow to the Arugal no doubt!" and then no credit for completing the quest.

**Comment by lasuax** [comment]
The issue is still there, tested today.

**Comment by Hasegawa007** [comment]
Issue still exists. After finishing the waves, she says the line but quest marker above her doesn't change into the one for completed quests and you can't finish the quest. 
![Screenshot (1318)](https://github.com/slowtorta/turtlewow-bug-tracker/assets/133974297/b0596d5b-74b4-4a77-ae2c-9f8d1147d0ce)

**Comment by emomilk** [comment]
Did this quest twice today. First one bugged out so we tried again and the second one work.

In the first run I used freeze traps to trap a few enemies as they entered the room. In the last wave the first enemy got caught in the trap and this somehow caused the other two enemies to stay outside the main room. Once the first enemy thawed out we killed him but the other two were still stuck in the small room outside the main room. We killed the last two enemies in the small room and the quest bugged. The reason was probably that the last two enemies, which we killed in the small room, did not engage the quest giver in combat.

In the second run we did not use any crowd control and allowed all enemies to walk into the main room freely so they all engaged the quest giver in combat and the quest was successfully completed.

So if you are having trouble with the quest, you could try that.

**Comment by Giperion** [comment]
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/10399905/d55a2c25-9690-431d-aa3f-d6aea18e788f)
Can't reproduce. Tried two times, and two times it completed without problems.
