### ISSUE TITLE
Cleansing the Songflower in Felwood

### ISSUE THREAD

**Issue by afizzler** [slowtorta/turtlewow-bug-tracker#1734]
Attempting to cleanse a corrupted songflower in felwood will not give you the intended world buff, Songflower Serenade.

**Comment by 9600bauds** [comment]
Most likely what happened here is that the corrupted flower respawn time and the non-corrupted flower respawn time are different, so if you're unlucky and someone else already purified the flower a while ago, there's a specific window of time where you'll cleanse the corrupted flower and the non-corrupted flower won't spawn because it's still in cooldown. Or it spawns, but a few minutes later, I don't remember.
Anyways this is really dumb but it's blizzlike
