### ISSUE TITLE
1% chaste enchants don't work on spells

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1762]
**Please, provide a clear description what the bug is:**

Dragu confirmed that the glove, helm and leg 1% haste enchants are supposed to increase spell speed as well. This is currently not the case.

Only my ring from cresent groove does both. Enchants don't

**Comment by geojak** [comment]
Also counterweight weapon enchant

**Comment by Kuz-Shaman** [comment]
Can there please be a response from a Mod? Just tell us if the spellhaste on enchants is intended to be added in the future or not. thanks!

**Comment by redmagejoe** [comment]
Tested on current version, and all haste items do in fact increase spell haste.

Fixed.

**Comment by geojak** [comment]
@redmagejoe you misread. this ticket isnt about the items. those half aways worked. this ticket is about the encahnts

**Comment by redmagejoe** [comment]
Looking at the spells on DB at least, it does not seem like they all work properly anyway even before getting into enchants.

[Haste 1](https://database.turtle-wow.org/?spell=13679) has Aura 140 and 65 incorrectly set at Value 2 instead of Value 1.
[Haste 2](https://database.turtle-wow.org/?spell=8815) has Aura 140 and 65 incorrectly set at Value 3 instead of Value 2.
[Haste 3](https://database.turtle-wow.org/?spell=13680) is missing Aura 65 at Value 3 and has Aura 140 incorrectly set at Value 4 instead of Value 3.
[Haste 4](https://database.turtle-wow.org/?spell=13681) is missing Aura 65 at Value 4.
[Haste 5](https://database.turtle-wow.org/?spell=13682) has the correct values.
[Haste 10](https://database.turtle-wow.org/?spell=18065) has Aura 140 and 65 incorrectly set at Value 11 instead of Value 10.

Haste in general needs to be reviewed.
