### ISSUE TITLE
(Druid) Savage Bite requires rage even with Clearcasting

### ISSUE THREAD

**Issue by Platinumcoated** [slowtorta/turtlewow-bug-tracker#1960]
after the 18.8. update Savage Bite can now benefit from Clearcasting, however it still requires rage. Savage Bite cannot be used unless the druid has 30 or more rage.

**Steps to reproduce the behavior with as much detail as possible:**
1. get Clearcasting through Omen of Clarity
2. notice Savage Bite is grayed out and unusable unless the druid has 30 or more rage

**Expected behavior. Describe how it should work:**
If the druid has Clearcasting, Savage Bite should be usable no matter how much rage the druid has. That is how all other bear abilities work too.
Maul, Swipe and Demoralizing Roar can be used and are not grayed out no matter how much rage the druid has, as long as he has Clearcasting.

**Comment by Testerrosaurus** [comment]
Still bugged as of 30.08.2022

**Comment by dan-personal** [comment]
Still bugged as of 5/10/22.

This surely is not a difficult bug to fix?

**Comment by SaxxonPike** [comment]
Some supplemental info, so we can help this along:

Spell ID for Clearcasting (Druid): 16870
https://database.turtle-wow.org/?spell=16870
https://www.wowhead.com/classic/spell=16870/clearcasting

Spell ID for Savage Bite: 45736
https://database.turtle-wow.org/?spell=45736

Even though the server may be discounting Savage Bite when it is used, it may be that the client doesn't know that Savage Bite is affected by Clearcasting- which would prevent an otherwise perfectly valid action from occurring.

**Comment by Jammyxx** [comment]
This is still bugged.

**Comment by Platinumcoated** [comment]
tested it now, works good for me

**Comment by Jammyxx** [comment]
After more testing this does work, however if a Maul is queued then the clear casting will not enable use of Savage Bite until the Rage requirement is met.
