### ISSUE TITLE
all windstones in souther twillight camp in sillithus dont respawn

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#1988]
**Please, provide a clear description what the bug is:**

all the widnstone in the souterh twillight camp doesnt respawn. They spawn on server restart only once

**Expected behavior. Describe how it should work:**

on the 2 nothern camps they rrespawn

this severly impact 20 man raids that want to do the lords because killing jsut 2 instead of 3 bosses is a big difference

**Comment by geojak** [comment]
![WoWScrnShot_082322_165239](https://user-images.githubusercontent.com/25199983/186190608-74191060-a76f-40fe-9396-afee4cce9e63.jpg)
![WoWScrnShot_082322_165047](https://user-images.githubusercontent.com/25199983/186190617-77eb7438-a6f6-47fe-9bbe-74f9dd57aa89.jpg)
![WoWScrnShot_082322_165050](https://user-images.githubusercontent.com/25199983/186190620-300cf725-7bd5-41e1-9136-0b4943fc6bc1.jpg)
![WoWScrnShot_082322_165237](https://user-images.githubusercontent.com/25199983/186190621-ac65249e-b3d2-40a2-9dc2-9d62b86876fa.jpg)

**Comment by Muigin** [comment]
Lesser Wind Stones are meant to have a 5 minute respawn timer.
Wind Stones are meant to have a 15 minute respawn timer.
Greater Wind Stones are meant to have a 3 hour respawn timer.

Some instances of these objects in Silithus are incorrectly / inconsistently set, and this will be fixed in an upcoming maintenance.
