### ISSUE TITLE
Magram Stormer's Lightning Shield has no delay between procs

### ISSUE THREAD

**Issue by SnorreP** [slowtorta/turtlewow-bug-tracker#2058]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Attacking a Magram Stormer in Desolace with a windfury proc causes all charges of it's Lightning shield to proc, and it will immediately recast it, creating for some dangerous situations for a lot of incoming dmg in a short amount of time potentially.

Screenshot of my combat log:
![image](https://user-images.githubusercontent.com/112721772/188207307-6afcfccf-b29a-4724-b967-a52c34373b1b.png)

**Expected behavior. Describe how it should work:**
I assume that Lightning Shield procs should have a delay just like the Shaman's own Lightning Shield

**Comment by slowtorta** [comment]
It's probably fixed in this update: https://forum.turtle-wow.org/viewtopic.php?f=63&t=4601

_Fixed an ancient bug that caused permanent periodic damage auras on creatures, like the disease cloud on abominations, to start ticking faster and faster over time, eventually one-shotting players that go near the creature if server is online long enough._
