### ISSUE TITLE
Double Brown Kodo at the <Kodo Mounts> vendor

### ISSUE THREAD

**Issue by MorlanOriginal** [slowtorta/turtlewow-bug-tracker#2064]
**Please, provide a clear description what the bug is:**
Harb Clawhoof sells double Brown Kodo instead of one Brown and one Gray.

**Steps to reproduce the behavior with as much detail as possible:**

1. Come to Mulgore in Bloodhoof Village
2. Talk to [Harb Clawhoof](https://database.turtle-wow.org/?npc=3685)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: [Harb Clawhoof](https://database.turtle-wow.org/?npc=3685)
Item: [Brown Kodo](https://database.turtle-wow.org/?item=15290) and [Brown Kodo](https://database.turtle-wow.org/?item=15277)

**Expected behavior. Describe how it should work:**
One of kodo should be recolored in gray.
![WoWScrnShot_090322_164039_cr](https://user-images.githubusercontent.com/112715239/188273482-8bd0adab-a0f5-48ba-950f-d52ca06607ba.png)

**Comment by FaeshaDawnwing** [comment]
If you look at the second kodo you linked, you'll notice it has a grey icon. Also, when you click on the wowhead-link in the database, it links to the Gray Kodo.
As visibile in this report: #https://github.com/slowtorta/turtlewow-bug-tracker/issues/2018
The issue is that both kodos got named Brown Kodo, even though they are actually still different colours and fully functional.
Shouldn't be a problem as long as you carefully look at the icon (once it's usable and no longer red), but a fix in the next patch would still be great to avoid confusion or prevent other player from buying the wrong kodo.

**Comment by MorlanOriginal** [comment]
Ye-ye. I know that they different in-game. I just want that description of one kodo was fixed for avoid confusions.
