### ISSUE TITLE
Lockboxes are being locked when you log out

### ISSUE THREAD

**Issue by DaveMustang69** [slowtorta/turtlewow-bug-tracker#2104]
**Please, provide a clear description what the bug is:**
If I log out with unlocked lock boxes in my inventory, when I log back in they are locked again

**Steps to reproduce the behavior with as much detail as possible:**

1. Open a lock box
2. Log out
3. Log in and your lock boxes will be locked again

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=5758

**Expected behavior. Describe how it should work:**

A rouge lockpicks the box. I log out. When I log back in, the box should still be unlocked.

![image](https://user-images.githubusercontent.com/56465794/189538413-182807d8-3349-4e69-97e9-df32b94a5365.png)

**Comment by Tinyfin-github** [comment]
Additional notes:

This bug manifests only if your lockboxes got opened in the trade window by another player.
If you open them by yourself , the bug does not manifest.

**Comment by redmagejoe** [comment]
This is STILL an issue.

**Comment by Wuzzin** [comment]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Have rogue lockpick https://database.turtle-wow.org/?item=4637 or https://database.turtle-wow.org/?item=4638
2. Didn't open for about 48 hours with several logoffs.
3. Lockboxes now show as "Locked" again and are not openable. Deleting WDB folder did not fix issue.
4. Shed a tear for your lost 1g tip.
5. ???
6. -Profit :)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=4637
https://database.turtle-wow.org/?item=4638

**Expected behavior. Describe how it should work:**
Have rogue unlock your lockboxes and have them stay unlocked for you to open later.
