### ISSUE TITLE
Cloak with +healing & Attack Power

### ISSUE THREAD

**Issue by zulnam** [slowtorta/turtlewow-bug-tracker#2121]
**Please, provide a clear description what the bug is:**
Please confirm this item is by design.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get item.
2. Ask wth are you supposed to do with it.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Item: https://database.turtle-wow.org/?item=81122

**Expected behavior. Describe how it should work:**
Item should either have spell damage (for a shaman or paladin) or no AP (for healers). The mix of Healing and Attack Power is something i've never seen before and _weird_.

**Comment by geojak** [comment]
This isn't for suggestion but bugs.

**Comment by zulnam** [comment]
It wasn't a suggestion. Those stats are counterintuitive to one-another and unique in the entire game, to my knowledge. Enough to make one thing it was an error when implementing the item (used healing instead of healing and damage).

If it's not the case, feel free to close.

**Comment by Velite12** [comment]
It is kind of like asking why blizzard made the lawbringer set healing focused plate with low healing and strength. Vanilla itemization is just counterintuitive like that until we start approaching the end patches when they figured out how to make gear for specific specs instead of catchall gear with a wide spread.

**Comment by slowtorta** [comment]
This item is working as intended! Not every item in the game is supposed to be useful  :)
