### ISSUE TITLE
Shaman Clearcast Elemental Focus can't refresh itself

### ISSUE THREAD

**Issue by zengrimm** [slowtorta/turtlewow-bug-tracker#2304]
**Please, provide a clear description what the bug is:**
Shaman Clearcast can not Refresh / Override itself after u have done two critical white hits in a row.

**Steps to reproduce the behavior with as much detail as possible:**

1. Get a Critical White hit and thus get Clearcast.
2. Optional Step: Use a shock spell to reduce Clearcast Count from 2 to 1.
3. Get another Critical White hit: This will not refresh the clearcast buff (neither duration nor Count).

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC:
Item:
Quest:
Spell: https://database.turtle-wow.org/?spell=45541
Object:

**Expected behavior. Describe how it should work:**
The Clearcast should override itself like for example Flurry from shaman does.

https://user-images.githubusercontent.com/116185888/196743849-f1423432-8b1f-4825-9902-d90b21d496fe.mp4

**Comment by Seberats** [comment]
This bug is really annoying

**Comment by Kuz-Shaman** [comment]
This bug is a huge issue for Elemental and Enhancement Shamans alike, the manasustain took a huge it as opposed to how it was over the last half year (before the 4 stack bug even). If you cant fix this, please just make it 80% Mana Reduction for 1 spell instead, this would be way better than how it is now.

**Comment by ratkosrb** [comment]
It's already fixed. It will go live in the next server update.
