### ISSUE TITLE
Freshly tamed pets can't learn any skills because the lack of skillpoints

### ISSUE THREAD

**Issue by thisiskt** [slowtorta/turtlewow-bug-tracker#2398]
**Please, provide a clear description what the bug is:**
Freshly tamed hunter pets don't have any points to spend on already learned skills.
**Steps to reproduce the behavior with as much detail as possible:**
Go to Arathi Highlands/Alterac/hillsbrad, tame a snapjaw or a mountain lion or a plains creeper.
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
A snapjaw or a mountain lion or a plains creeper.
NPC: https://www.wowhead.com/classic/npc=2563/plains-creeper
Spell: https://www.wowhead.com/classic/spell=5149/beast-training
**Expected behavior. Describe how it should work:**
I used to be able to teach tamed pets anything, regardless of loyalty levels or skillpoints. I don't know about any change about this, neither did my guild.
I was advised to relog after deleting WDB, didn't help. I currently have the plains creeper in my stables, still isn't able to learn anything other than Growl which is 0 points.
Edit: My character is a HC dude, named Enginuity.

**Comment by D4nSch** [comment]
Fresh tamed pets always have 0 training points, the actual formula is **(level)*(loyalty-1)**. Since you start with loyalty level 1 you get zero points at the start. If you ever were able to train your pet skills other than growl while having 0 training points it was simply bugged.
https://www.wow-petopia.com/classic/training.php
