### ISSUE TITLE
Earth shield

### ISSUE THREAD

**Issue by vkekd** [slowtorta/turtlewow-bug-tracker#2653]
The first charge of earth shield doesn't heal you. In the combat log you can see that the damage occurs first and the heal second but you just dont get the heal.

1.- Use earth shield
2.- Get hit once while you are at full hp
![erthsld](https://user-images.githubusercontent.com/110942912/210583968-bce768bb-0c2a-48e3-a4bc-4107782f7d4f.png)

**Comment by SolarGuru** [comment]
I believe that (in spite of combat log) earth shield heals you BEFORE damage applied. So, if you have full HP, first charge of shield is wasted as overheal. If so, it's better to apply earth shield effect AFTER damage applied or even IN damage calculation.

**Comment by Zeyla-TW** [comment]
Indeed, in spite of the combat log's message this is how Earth Shield works (triggering the heal before the damaging attack). This actually work out to be MORE beneficial than the other method in many cases, since that means attacks that would just barely kill you can first proc the heal and you can survive with a few points of health. There actually many reactive spells that function in this way as well, as it is simply part of the game's underlying systems with reactive spells. Working as intended.
