### ISSUE TITLE
Dark Iron Pulverizer

### ISSUE THREAD

**Issue by PizzaCompanyCom** [slowtorta/turtlewow-bug-tracker#2726]
Weapon Dark Iron Pulverizer, passive effect: 8 sec. stun target. Real target stun no more than 2 seconds. Where is 6 more seconds?

Item: https://database.turtle-wow.org/?item=11608

Video usage Dark Iron Pulverizer: amhmkm.com/111.webm

**Comment by geojak** [comment]
Are you usung shagu plates? My addon shows also 2s when un fact stun last longer

**Comment by PizzaCompanyCom** [comment]
I don't use an addon. Please watch the video, I made a cut. Stun for no more than 2-3 seconds.

amhmkm.com/1111.webm

**Comment by redmagejoe** [comment]
Can confirm, only a 3 second stun with no diminishing returns in play. The proc rate is so obscenely low, it took me 10+ minutes of testing just to get a proc, so it feels like being robbed when it finally does go off and gives such a minor effect.

**Comment by Jeradooka** [comment]
Please, provide a clear description what the bug is:
-Dark Iron Pulverizer stun length is too short. Tooltip description says it will stun for 8 seconds, but the stun does not last that long.

Steps to reproduce the behavior with as much detail as possible:

Equip Dark Iron Pulverizer.
Attack NPC's or Players until the proc occurs.
Count the duration of stun length.
IDs of affected creatures, items, quests or spells with a link to the relevant page:

Item: https://database.turtle-wow.org/?item=11608

Expected behavior. Describe how it should work:
It should stun for a full 8-seconds, consistent with what the tooltip states.
