### ISSUE TITLE
Fel Energy bug

### ISSUE THREAD

**Issue by ZorgDarkness** [slowtorta/turtlewow-bug-tracker#2734]
Warlocks can cast Fel Energy when they are at demonology spec, than they can respec to other spec and stell have Fel Energy buff on tham as they in anothey spec wich is not have Fel Energy talant learned at thair taland tree
Spell: https://database.turtle-wow.org/?spell=18792

**Comment by balakethelock** [comment]
Copying my other comment since it's a duplicate
It's not a bug and not an exploit. This discussion was finished a long time ago and they decided they remove succubus sacrifice but not the other sacrifices.

Don't revive old topics that you are ignorant about
https://discord.com/channels/466622455805378571/810850818537685013/1009343879016878130
