### ISSUE TITLE
got stuck at darkmoon fair

### ISSUE THREAD

**Issue by Prehn81** [slowtorta/turtlewow-bug-tracker#275]
**Please, provide a clear description what the bug is:**

tryed open the tonk controler and got stuck on caracter galandrial

**Steps to reproduce the behavior with as much detail as possible:**

1. could not move, but my spells worked fine
2. auto unstuck did nothing
3. wormhole ported me to SW but could still not move
4. logged out and in, did not solve problem

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by redmagejoe** [comment]
This is still broken. Tonk instantly dies, the camera never switches to the "controlling tonk" behavior, and character is basically frozen indefinitely.

**Comment by Zeyla-TW** [comment]
This seems to be an issue with spell ID 24935, which is bound to the Tonk Control Console gobject. The spell's first effect is a script that is bound to the spell in order to control the Tonk, while the spell's second effect is to root the player in place for the duration of the spell (5 minute duration to prevent character movement while controlling tonk) and since the spell isn't shown in the buff list, the script failing causes you to be stuck in place for 5 minutes until the spell expires naturally. I do not currently know if the script itself is the issue or if the spell's settings to trigger the script are not configured properly to target the player/tonk in the correct order.

**Comment by Letic92** [comment]
@redmagejoe tried to reproduce without success.

Used item https://database.turtle-wow.org/?item=22728, also tried with casting self spell https://database.turtle-wow.org/?spell=24935 and everything went well, no stuck, no problem with cam etc.
