### ISSUE TITLE
"Sarkoth" quest minor typo

### ISSUE THREAD

**Issue by MorlanOriginal** [slowtorta/turtlewow-bug-tracker#2776]
**Please, provide a clear description what the bug is:**
In quest descryption missing one paragraph indent.

**Steps to reproduce the behavior with as much detail as possible:**

1. Come to Durotar in Valley of Trials;
2. Talk to [Hana'zua](https://database.turtle-wow.org/?npc=3287) and take [Sarkoth](https://database.turtle-wow.org/?quest=790).

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: [Hana'zua](https://database.turtle-wow.org/?npc=3287)
Quest: [Sarkoth](https://database.turtle-wow.org/?quest=790)

**Expected behavior. Describe how it should work:**
Add missing paragraph indent.
![WoWScrnShot_012923_171844_cr](https://user-images.githubusercontent.com/112715239/215352036-23c819c2-35d2-4494-bc67-c71c46c56688.png)

**Comment by redmagejoe** [comment]
https://www.wowhead.com/classic/quest=790/sarkoth

This is a Blizzard quest, and the text is correctly formatted as seen here on their page.

**Comment by MorlanOriginal** [comment]
Argument that Blizz don't fix some grammar and logical mistakes in their creation in almost twenty years...

In this exactly case i follow logic. Yeah, periodically i can do mistake in grammatics, english not my native.
So if i see smtn that can become better, why not post it?

PS: atleast 2 Blizz long-live text mistakes were fixed thru my tickets here.

**Comment by redmagejoe** [comment]
I have no idea what any of that meant. I will reiterate, these are two paragraphs, not three as you seem to be assuming. There is also no indentation in quest dialog. If you are suggesting it requires a carriage return, it would only be the case if the highlighted text were two separate paragraphs, which they are not. I believe you are confused because the bounding dimensions of the quest window force "Please" onto the next line, and you perhaps mistook this as the beginning of a new paragraph.

**Comment by mikefirefly** [comment]
This bug report is invalid but I'd cry of joy if these were the only bugs left unfixed on the server...

**Comment by slowtorta** [comment]
Fixed on the next update.
