### ISSUE TITLE
no cd on battery powered mcp

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2802]
**Please, provide a clear description what the bug is:**

the battery powered manual crowd pummeler that engies can craft not have a cd.
why is this an issue?
becuase if you spamm click it you might burn trough mutiple batteries in seconds for nothing.
if it had a small cd, even just 5 seconds, players would be protected from wasting batteries by multie clicking accidently
this would make using this weapon alot more comfortable for players.

https://database.turtle-wow.org/?item=60099
https://database.turtle-wow.org/?item=9449

**Expected behavior. Describe how it should work:**
short cd on usage of 5s

**Comment by Meridaw** [comment]
you can use macro's to limit it. `/run i=0 m=0 while not (GetPlayerBuff(i)==-1) do if (strfind(GetPlayerBuffTexture(GetPlayerBuff(i)),"Spell_Nature_Invisibilty")) then m=1 end i=i+1 end if m==0 then UseInventoryItem(16); end`  this one will use main hand buff when you're missing the haste buff. 

in these days with global energy crisis and renewable energy demand, we need more effective batteries. so maybe add a recipe to recharge a empty battery. so that we can recycle them.

**Comment by geojak** [comment]
Greta macro thx
