### ISSUE TITLE
Warrior Charge Arms Talent Rage Calc

### ISSUE THREAD

**Issue by Chrisrtc** [slowtorta/turtlewow-bug-tracker#2847]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Skill improved Charge as a Warrior
2. Dont see additional rage
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by redmagejoe** [comment]
Rank 1 Charge grants 9 Rage
Rank 2 Charge grants 12 Rage
Rank 3 Charge grants 15 Rage

Therefore with the talent, you should be getting:
12/15
15/18
18/21

Please double-check that these are the values you are receiving, and please post screenshots and more details in the future. Without describing exactly how much Rage you are getting versus how much Rage you think you should be getting, no conclusions can be made as to whether the feature is bugged or if perhaps you are misunderstanding an otherwise-working feature.
