### ISSUE TITLE
Issuance of cross-fractional loot

### ISSUE THREAD

**Issue by TorTun** [slowtorta/turtlewow-bug-tracker#2878]
At the moment, in order to issue horde loot by the alliance master, it is necessary to transfer the rights to issue loot to the horde player, since the alliance player does not see the horde loot and, accordingly, cannot distribute it, which complicates the distribution of loot in raids.

pls help😭

**Comment by redmagejoe** [comment]
For clarification, is this a Master Loot issue?

**Comment by vkekd** [comment]
> For clarification, is this a Master Loot issue?

This is mostly for faction specific items like paladin/shaman tiers, natural alignment crystal/scrolls of blinding light, aq20 paladin/shaman books/totems, etc.
This also happens sometimes to items that are not faction specific like in MC ive seen it happen with talisman of ephemeral power, quick strike ring, flame guard gauntlets, etc.
The only raid that i havent seen seen this issue is naxx. Horde can see paladin librams or restristed class trash items and vice versa.

**Comment by Haaxor1689** [comment]
No cross-faction server (vanilla/tbc/wotlk) had a proper solution for this, if master looter is let's say Alliance player, if there is a Horde only item like a quest starter, he just won't see it. Also unique items like rings and trinkets won't show up for him if he already has them. You sure it's not because of that?

**Comment by Haaxor1689** [comment]
What you can do to work around it is to distribute all loot that you can, roll for items ML can't see and then change to FFA so whoever won can loot it.

**Comment by vkekd** [comment]
No i never had problems seeing rings and trinkets that i had already and yeah, like i said putting it on FFA or giving ML to another person solves the issue but if they somehow work on a solution so the master looter can see all the loot and distribute it by himself it would be better

**Comment by Zeyla-TW** [comment]
I believe this could potentially be resolved by editing the drop tables on the server (or possibly merging them) so that both factions can view every table that the boss drop list pulls from. Some bosses can have up to 3 or 4 drop tables (some with 100% chances like ony heads or heart of hakkar) and iirc (I haven't played with SQL drop tables in quite a while) I BELIEVE that the tables themselves are flagged for view by a certain faction.

**Comment by Gurky-Turtle** [comment]
This should have been solved a few patches ago
