### ISSUE TITLE
Harvest Golem quest Gazzirik

### ISSUE THREAD

**Issue by Loon15** [slowtorta/turtlewow-bug-tracker#2896]
**Please, provide a clear description what the bug is:**
The quest asks to defeat both Gazzirik and F.W but just clicking on Gazzirik counts that part of the quest as complete.
**Steps to reproduce the behavior with as much detail as possible:**

1.Obtaining Harvest Golem quest 
2. Clicking on Gazzirik then completes part of quest
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=Gazzirik

Quest: https://database.turtle-wow.org/?quest=40485

**Expected behavior. Describe how it should work:**
Quest should not complete until you've actually killed Gazzirik.

**Comment by slowtorta** [comment]
@ratkosrb I think this quest handling has been moved to DB, now gossip-hello/right click on the goblin is triggering the objective for slain to get completed.

**Comment by ratkosrb** [comment]
The issue happens because turtle core is missing on talk script_id for gossip_menu table, and instead its hardcoded to always give credit for npc you are talking to when opening gossip. So because this quest requires you to kill the npc, but the npc only becomes hostile after talking to it, you don't even need to fight him, since objective is completed as soon as you open the gossip, because of that hardcoded logic which applies to all creatures.

This commit needs to be ported from vmangos.
https://github.com/vmangos/core/commit/ce8cc4a6426b9eded209419718ddd0f38db1f0be
