### ISSUE TITLE
Parry

### ISSUE THREAD

**Issue by Babygrim** [slowtorta/turtlewow-bug-tracker#2903]
**Please, provide a clear description what the bug is:**
Mobs can parry attack while stunned. (I assume that means they can also dodge and block).

**Steps to reproduce the behavior with as much detail as possible:**
Use Hammer of Justice on random mob and hope for RNG

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
-----

**Expected behavior. Describe how it should work:**
As native wow Tip says, creatures cannot dodge/block/parry while stunned.
This is proof screenshot of my combat log.
![image](https://user-images.githubusercontent.com/104301713/221404703-e7f0d4c2-56e4-434c-8987-e7997f97b876.png)

**Comment by redmagejoe** [comment]
This is indeed not working as intended and should be investigated by a core developer. Can confirm this behavior on Live.

**Comment by Zeyla-TW** [comment]
I just tested this with a fast weapon many times on an expert training dummy, and so long as I cast the hammer of justice before beginning auto-attacks it has been completely unable to dodge or parry my attacks until the stun wears off. The only time I can somewhat replicate this issue is when I'm already auto-attacking the target before using hammer of justice, in which case the auto-attack's attack table has already been resolved at the very beginning of the swing, then the stun hits, and the resolved auto-attack's animation finally lands and can result in a parry. (since it technically occurred well before the combat text appears)

**Comment by twowTurtReynolds** [comment]
I spam `.aura 18063` on a mob 20 times to see this easily, and gave myself 500% haste. 

![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a3d02a8c-767b-42f1-95c1-5e85a3a5e2d8)

Looks fixed :)
