### ISSUE TITLE
Seal of the Crusader does not increase attack speed by 40%

### ISSUE THREAD

**Issue by ConcernedTurtler** [slowtorta/turtlewow-bug-tracker#2923]
**Steps to reproduce the behavior with as much detail as possible:**

1. Equip weapon with 1.6 attack speed.
2. Use Seal of thee Crusader Rank 3
3. Check attack speed

Result:
Attack speed reduces from 1.6 to 1.14 which is only a 29% increase.

**Comment by cyaohiri** [comment]
The calculation is done based on the attack speed, not attack time. Attack time of 1.6 corresponds to 0.625 attacks per second (1/1.6). Increasing that by 40% gives us 0.625 * 1.4 = 0.875 attacks per second, which corresponds to attack time of 1.14 (1/0.875)

**Comment by geojak** [comment]
The real issue with seal of crusader is
It was custom changed to give 30%-60% attackspeed depending on rank. Blizzlike is static 30%. But the, devs kept it so, that your dmg is reduced equally to your increased attackspeed.

This should be chnahed to dmg is reduced by 30% static but the actual attackspeed is 30-60%.
At lvl 60 you effectively now got a flurry seal you can build for pure physical dmg build instead of using seal of righenouenss which scales with sp or Soc which scales with both sp and physical stats.

Seal of crusader is currently a useless dead seal and I don't understand the custom change to it as it doesn't fix it at all. 
Thiught we talked avout this, before on the forum.

**Comment by Zeyla-TW** [comment]
100% haste would mean 100% more attacks in the same period of time. As previously pointed out, 40% more attacks on a base speed of 1.6 (1 attack per 1.6 seconds) would be 1.4 attacks per 1.6 seconds. Reducing that fraction down to a numerator of 1 attack, we get a denominator of 1.142857~ or about 1.14 when rounded.

All that being said, working as intended.

**Comment by Vrerk** [comment]
Ah, that's disappointing. 
Thanks for the replies, sorry for wasting your time.
