### ISSUE TITLE
Majordomo reset on pull 

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#2932]
**Please, provide a clear description what the bug is:**

Last mc on majordomo on pull suddenly all desoawned, immidietly respawned without marks, then wiped us becuaw with marks gone it was chaos

**Steps to reproduce the behavior with as much detail as possible:**

1. Set marks on majordomo and adds 
2. Pull 
3. ??? (hasn't happened before) 
4. The depsawn and respawn immideitly without marks 

**Expected behavior. Describe how it should work:**

This should not happen, or atleast marks should be kept. Feign death was not involved in pull

**Comment by Zeyla-TW** [comment]
This is most often attributed to someone pulling and immediately resetting the boss with feign death, vanish, divine intervention, flask of petrification, etc. then immediately initiating combat due to still being too close after the reset. If you can provide video evidence of this occurring without any such effect being used then it can be further investigated, but for now it cannot be reproduced with the information given.
