### ISSUE TITLE
LORD KAZAAK

### ISSUE THREAD

**Issue by Altgf-spelladin** [slowtorta/turtlewow-bug-tracker#2989]
I am not sure if it belongs to Bug Tracker, cause I am not sure if it's a bug or not.

Can we somehow fix the issue with Lord Kazaak being spawn camped by warlocks?
Warlocks can and do now farm Kazaak on each spawn in group of 10 by enslaving the mobs around, which can tank him effectively.

This means, that it's impossible to get Kazaak killed by any raid group ever.

Would be nice if you made those elites demons from Tainted Scar immune to Enslave Demon.

Thanks a lot :)

**Comment by balakethelock** [comment]
Not a bug, but a game design debate.

10 people IS a raid group just like 10 warriors can kill him with a few restorative potions and sippy set and a healer or two. Warlocks can't kill it alone, they need healers and dispellers. I don't see why this flavorful little interaction shouldn't be allowed **just because you feel entitled to be handed the boss on a silver platter?**

The issue to be honest is that Kazzak has two highly sought after bis items in the middle of a very crappy loot table, not that people are camping the boss. If you want those items, you have to beat everyone else to the boss.

Even if they wanted to do this change, they can't simply make them immune to enslave because enslaving them is very important for the warlock quests that happen there.

**Comment by Zebouski** [comment]
This post belongs to https://forum.turtle-wow.org/viewforum.php?f=14 not here, this isn't a bug, just a meta that you don't enjoy.

**Comment by ConcernedTurtler** [comment]
Make world bosses summonable instead of just a random spawn. Problem Solved.

**Comment by suggney** [comment]
beating a dead horse here, but you're lying about warlocks doing that. i've attended the last couple kazzak kills and the lowest population one (which was the most recent) had eighteen people, one of which was a dedicated warrior tank. the warlocks used the demons around kazzak for extra dps, not to 'tank it' or 'cheese it'. furthermore, why would locks farm kazzak? the pants aren't for them, they get better in multiple raids

**Comment by lyssebabz** [comment]
When has this happend? last 3 lord kazzak kills have not been from warlocks

**Comment by balakethelock** [comment]
It's absurd that they went against intended game mechanics and made all the demons immune to enslave. Might as well completely remove the spell now! It's useless with basically no demons above 55 that it works on, and even the lower level ones it randomly breaks. you can't even take a level 5 satyr to roleplay with.

This ninja change not even mentioned in the patchnotes is hurting warlock identity

**Comment by Doombabe** [comment]
Can confirm that the original poster is lying about this. I know for a fact that multiple world boss pugs have been successfully and consistently killing Kazaak since at least 2/26/2023. That's obviously not a very long time, but for the OP to make that accusation on 3/10 would have to mean that it was happening around this time, which is just not the case, and doubtfully ever has been. It would be pretty difficult to coordinate a group of 10 warlocks to do this consitently, given the low population of them on the server, and like somebody else said, they couldn't even do it alone. 

How about you people actualy do your job and due diligence by properly investigating and using common sense to address random comments like this.

**Comment by Doombabe** [comment]
And furthermore, actually open up the discussion to the community and make a proper announcement rather than just slipping the change in like nobody would know, and then auto-close somebody else's bug report with a lazy comment like, "this is not a bug", without giving any proper justification for the change.

**Comment by Abunara** [comment]
> Make world bosses summonable instead of just a random spawn. Problem Solved.
I have to agree on this one, great idea!
