### ISSUE TITLE
Spirit Amor Talent is not working on Troll Shaman

### ISSUE THREAD

**Issue by Alorgg** [slowtorta/turtlewow-bug-tracker#3012]
Hey, 

i just get + 10% Armor. I Just calculated it. The 30 From my Shield are Missing!
It feels like that this error just happens on Troll Race

**Comment by Zeyla-TW** [comment]
Please un-equip and re-equip your shield after changing talents in order to update the armor values. This is a known issue with changing talents, and loading into instances/re-logging should also cause the armor update to occur. Due to the nature of the talent swap system and the ease of the talent naturally updating itself through gameplay, this is a very niche and minor issue. If your problem is being caused by something other than this, please address it here and we can re-open this issue.

**Comment by Alorgg** [comment]
Hey Zeyla,

i still dont get the Extra 30% Armor on my shield!
Tried everything, i can just mention again that all shamans with this problems are Troll:)

may you guys check this again, please?:)

Thank you in advance
