### ISSUE TITLE
Hero of the Stormpike bugged out, cannot be collected

### ISSUE THREAD

**Issue by Snapps1** [slowtorta/turtlewow-bug-tracker#3163]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Quest Hero of the Stormpike cannot be collected or completed after Battle of Alterac
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=13816
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=8271
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Quest should be collectable and completable I guess

**Comment by Dozor51** [comment]
Same problem, Just a bit more information:
I did more than just the first AV because I thought the qs may only appear after the first or inside the second as the Npc is standing next to the alliance boss during AV... (obv. it didn´t)
And I checked after my reputation rose and that didn´t unlock the quest either..

**Comment by redmagejoe** [comment]
The quest is no longer available on Turtle since the implementation of Old Alterac Valley.  The method by which to get the items displayed in that quest come instead from the Korrak the Bloodrager quest.

https://database.turtle-wow.org/?item=19106#reward-of:0+5+1+2
