### ISSUE TITLE
Sap/gouge/CS/KS/feint and weapon procs.

### ISSUE THREAD

**Issue by Sringaram** [slowtorta/turtlewow-bug-tracker#3168]
Previous issue: https://github.com/slowtorta/turtlewow-bug-tracker/issues/3097

After the fix, those abilities trigger all weapon procs and poisons, not only non-damaging stuff. Meaning sap and gouge break themselves with offensive procs. You also get unstealthed and put in combat in the case of sap.

**Comment by ratkosrb** [comment]
Is there evidence they should not proc damaging effects? There is no such proc exclusion mechanic used anywhere else in the game. Its always a chance to proc any weapon based effect. Chance on hit effects dont have proc flags, neither do weapon enchants.

And the evidence from classic seems to prove the opposite. There are threads on the Blizzard forums from people complaining about Sap triggering damaging effects and breaking itself.

Read this topic for example.
https://us.forums.blizzard.com/en/wow/t/sap-applies-poisons/309762

Some quotes:

> Not sure if it was in-line with vanilla but sap sometimes applies my main hand poison or even my chance on hit effect.
> 
> Running improved sap this could lead to it breaking your sap and rendering it useless

> If that’s the case then what about on-hit weapons. I had Toxic Revenger which was also triggered by a sap when the weapon technically isn’t being used. Same goes for poisons too I suppose, bad design

> Yeah it can proc poisons and chance on hit stuff too.
> I’ve had sap break a couple of times due to the bleed proc from Barman shanker

It looks to me like the current behavior matches the official servers?

**Comment by imaglcian** [comment]
Technically this issue shouldn't be a thing, I remember in Classic you could proc something like Vis'kag on a Sap, said sap would not break & the proc would go through. Although I did have to come to a middle-point, as this fix was rejected last year.
What is bugged however, is the fact that stealth now has a chance to break on Crippling Poison procs.

**Comment by Sringaram** [comment]
> Is there evidence they should not proc damaging effects? There is no such proc exclusion mechanic used anywhere else in the game. Its always a chance to proc any weapon based effect. Chance on hit effects dont have proc flags, neither do weapon enchants.
> 
> And the evidence from classic seems to prove the opposite. There are threads on the Blizzard forums from people complaining about Sap triggering damaging effects and breaking itself.
> 
> Read this topic for example. https://us.forums.blizzard.com/en/wow/t/sap-applies-poisons/309762
> 
> Some quotes:
> 
> > Not sure if it was in-line with vanilla but sap sometimes applies my main hand poison or even my chance on hit effect.
> > Running improved sap this could lead to it breaking your sap and rendering it useless
> 
> > If that’s the case then what about on-hit weapons. I had Toxic Revenger which was also triggered by a sap when the weapon technically isn’t being used. Same goes for poisons too I suppose, bad design
> 
> > Yeah it can proc poisons and chance on hit stuff too.
> > I’ve had sap break a couple of times due to the bleed proc from Barman shanker
> 
> It looks to me like the current behavior matches the official servers?

I'm not sure but if that's the case then I'd rather have the previous implementation which made proc weapons viable and allowed you to use offensive poisons in main hand for leveling/grinding/dungeons. The current tradeoff for being able to pull some duel shenanigans isn't worth it and it also ruins the most used PvP weapon (MSA).

The current implementation is downright horrible overall.

**Comment by ShiraZen** [comment]
Here's my thought:

Sap and Gouge simply require a weapon because WoW doesn't want you to be using them while **Disarmed**. That's the only reason. Same with other skills like Sinister Strike.

However, Sap and Gouge being tied to your MH and them NOT procing effects shouldn't be mutually exclusive - basically they SHOULD *require* a MH weapon, however they SHOULD NOT proc effects.

Because if they did proc effects, Sap and Gouge would have "built-in fail chances", so to speak. 
If you used any type of DPS poisons, had any type of MH weapon proc, or had an elemental damage proc on your gear (all very common things), you'd Gouge/Sap, and the opponent would instantly be free again. In PvE or PvP, both could often be a death sentence.

Cheap Shot is different because you cannot accidentally break the stun*. Cheap Shot is intended for you to DPS directly afterwards, so if it procced weapon effects it wouldn't be detrimental to the skill's intended use. 
Remember: after a Cheap Shot or Kidney Shot - the player will continue Auto Attacking afterwards.
After Gouge and Sap - they will NOT Auto Attack afterwards, because of course you'd instantly break your CC tools.

Like, I have been sapping in dungeons w/ Instant Poison for months without issue. I could care less about giving them Mind Numbing - I just want the target to be sapped. You can't even remove poisons from weapons.

So if you accidentally apply Instant Poison, you're just fucked unless you can overwrite it? That makes no sense at all. The game cannot be intended to be played that way. If it is, then the design itself is fundamentally flawed.

Half of Rogue's best CC tools not being able to properly work with a bunch of gear, and 50% of the poisons MH, is a huge issue  for both PvE and PvP.
