### ISSUE TITLE
Everything makes you lose Combo points as a Rogue

### ISSUE THREAD

**Issue by HuMa69** [slowtorta/turtlewow-bug-tracker#3326]
Theres something clearly wrong on this combo point system, if you cancel target to stop autoattack you lose all your CP, if you kick other target you lose your CP, same with gouge,blind,sap..... this makes rogue very frustrating in PVP you can only tunnelvision or you will lose your CP..... even if you use a cheap shot macro with cleartarget to generate points while sapped with no autoattack you will lose all your CP and this is so bad..... 

How should it works: You can never lose your CP unless you make damage to other targets

**Comment by Sringaram** [comment]
This is sadly intended.

Pretty much all other pservers use the TBC combo point system where you only lose points on your current target if you generate a point on another. Even classic worked like that.

I hope it's changed one day because the current implementation only punishes proper player and promotes tunnel vision in PvE while also unnecessarily hurting the class in PvP.

**Comment by HuMa69** [comment]
This needs to be adressed, it makes the class to be played at 30% of his capabilities, rogue have a nice CC arsenal that cant be used only in 1VS1 and thats its so sad....

**Comment by welpenhund** [comment]
It's not just rogues, same happens on druid...
I keep my target focused but the moment i mouseover heal or dispel a teammate (means i still have my target focused, mouseover macro not changes my target) all combo points are lost while still having my target focused.

**Comment by HuMa69** [comment]
Then they should add TBC CP system, every 1.12.1 server have this feature, even classic 2019 had it....

**Comment by Muigin** [comment]
Working as intended. If you'd like to suggest a change to the behavior, please use the suggestions forum.
