### ISSUE TITLE
Enchant Gloves - Minor Haste Bug

### ISSUE THREAD

**Issue by TooHighOnLife** [slowtorta/turtlewow-bug-tracker#3357]
**Please, provide a clear description what the bug is:**
The Enchant says 1% attack AND cast speed but it is not giving the cast speed only the attack speed
**Steps to reproduce the behavior with as much detail as possible:**

1. Enchant gloves with minor haste
2. Check casting speed is still 2.5s on Frostbolt
3. Test with Batu'kar of the Second Khan and it lowers speed to 2.48 with no gloves on
4. put gloves on speed still 2.48 with staff on and gloves
5. Glove enchant not working as shown in the enchant description

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=13948

**Expected behavior. Describe how it should work:**
The enchant working as described giving true 1% haste to spells as well

**Comment by Letter-E** [comment]
Any universal haste effect on turtle WoW consists of three auras combined into one effect:
**Aura # 138: Haste - Melee** for melee attack speed, with a base value of **"0"**.
**Aura # 140: Haste - Ranged** for ranged attack speed, with a base value of **"-1"**.
**Aura # 65: Haste - Spells** for casting speed, with a base value of **"-1"**.

I've successfully tested the following haste effects for melee attack speed and casting speed increase. Take a look at the listed aura values for comparison:

**"Haste 1"**: https://database.turtle-wow.org/?spell=13679, offering 1% haste on a Hatereaver Cog.
The aura values are set up like this:
**Aura # 138: Haste - Melee** is set to **"1"**.
**Aura # 140: Haste - Ranged** is set to **"2"**.
**Aura # 65: Haste - Spells** is set to **"2"**.

**"Haste 2"**: https://database.turtle-wow.org/?spell=8815, offering 2% haste on a Shroud of Haunted Torment.
The aura values are set up like this:
**Aura # 138: Haste - Melee** is set to **"2"**.
**Aura # 140: Haste - Ranged** is set to **"3"**.
**Aura # 65: Haste - Spells** is set to **"3"**.

**"Haste 3"**: https://database.turtle-wow.org/?spell=13680, offering 3% haste on a Whip of Encouragement.
The aura values are set up like this:
**Aura # 138: Haste - Melee** is set to **"3"**.
**Aura # 140: Haste - Ranged** is set to **"4"**.
**Aura # 65: Haste - Spells** is set to **"4"**.

**Minor Haste** gloves enchantment: https://database.turtle-wow.org/?spell=13928, as it is right now, provides *1% melee haste*, *0% ranged haste* and *0% spell haste*.
This is due to the three aura values being set incorrectly, like this:
**Aura # 138: Haste - Melee** is set to **"1"**.
**Aura # 140: Haste - Ranged** is set to **"1"**.
**Aura # 65: Haste - Spells** is set to **"1"**.


I think the solution might be this simple:
Give **"Minor Haste"** the same values as **"Haste 1"**:
**Aura # 138: Haste - Melee** with a value of **"1"**.
**Aura # 140: Haste - Ranged** with a value of **"2"**.
**Aura # 65: Haste - Spells** with a value of **"2"**.
