### ISSUE TITLE
cat figurine Gold farm 

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#3359]
Disclaimer from the official rules it's forbidden:
"Abuse or promote abuse of any bug or exploit to obtain gold, experience, items, reputation, kill NPC's, kill players etc."

Anyone seeing this. Do not use this ingame.

**Please, provide a clear description what the bug is:**
![image](https://user-images.githubusercontent.com/25199983/235327815-b7835872-ad16-4f40-8bf4-e4b8fb8a1639.png)
![image](https://user-images.githubusercontent.com/25199983/235327853-c6b25761-b379-47f0-87f7-8a957bfbda51.png)

1. go to the cat figurien in dakrshore, keep looting them until you get the ghost saber spawn
2. loot the cat figurine, the figure does not despawn when the ghost saber spawns
3. 100% of the times a lvl 20 ghost cat will spawn
4. kill
5.  loot new trinket that summon a cat, its unique
6. vendor the trinket for 30s on your mobile vendor pet
7. since the cat figure didnt despawn, loot it again
8. another cat, another trinket, another 30s
9. keep going

if you are leatherworker you can even skin

**Expected behavior. Describe how it should work:**

the cat figure should despawn on loot and respawn later

**Comment by Nemoose** [comment]
It is definitly a bug, because the figurine should respawn after minutes AND there should only be a few percent chance to spawn a Ghostsaber when opening one.
When i went there a year ago to tame one for my hunter, most figurines did nothing and there is one figurine with the descriped bahavior of instant respawn and always spawning a Ghostsaber.
The GM probably didn't understand what you where asking or doesn't know how the object should work. If i where close by and see someone do it (eventhough the Gold/hour is kind of normal or eben low for a level 60) i would report it.

**Comment by Nemoose** [comment]
It is definitly close to the best farming spots at level 60, with also around 100g/h, maybe even better, i would say you can spawn/kill/loot/sell in under 6-7s. Never the less its only usable with a donation item, i guess we don't have to worry that bots will do this. It should still be corrected to normal behavior, because of the new version of the guardian item, else it's a free loot for every char from level 15+ insteat of a rare item you farmed for.
