### ISSUE TITLE
Can't blink out of  Bash

### ISSUE THREAD

**Issue by Anleihein** [slowtorta/turtlewow-bug-tracker#3364]
Can't blink out of  Bash

Mages should be able to blink out of stuns

Mob: https://database.turtle-wow.org/?npc=61074

Spell bash: https://database.turtle-wow.org/?spell=25515
Spell Blink: https://database.turtle-wow.org/?spell=1953

![image](https://user-images.githubusercontent.com/132210576/235357445-e7c0e60d-c820-4b8a-a97f-a9bb0ad050c0.png)

**Comment by jlautenbach** [comment]
Looking into (the expected behaviour as well as, but more so, at the unexpected behaviour of) this report. Will keep this issue updated. Thanks for reporting @Anleihein!

- Niralthas

**Comment by balakethelock** [comment]
Important note: You can't change the spell id itself, because it's also used by Lieutenant General Andorov in AQ20 (the helpful npc that aids you in 2nd boss), and if you change it you might bug out aq20. I guess if you want to fix it you can give the Highvale Gorillas a different stunning spell altogether. Or just remove it cause people always complain about those bashes.

**Comment by Zebouski** [comment]
Is this in the new tel abim zone? Its just that specific stun is bugged/mislabeled. https://github.com/slowtorta/turtlewow-bug-tracker/issues/2576

I was in pvp the other day, you can blink out of normal stuns.

**Comment by balakethelock** [comment]
The solution is so simple to be honest, just give them a different stun spell. Who thought giving General Andorov's bash ability to a mob is a good idea.

**Comment by Muigin** [comment]
#2576
