### ISSUE TITLE
Flourish, Slice and Dice can be overridden by shorter duration versions

### ISSUE THREAD

**Issue by RUTHINAS** [slowtorta/turtlewow-bug-tracker#3367]
**Please, provide a clear description what the bug is:**
Using Flourish or Slice and Dice grants a buff which varies in duration based on the amount of combo points expended. The strength of the effect is always the same.

When a high duration buff is already affecting the player, they can recast either ability with fewer combo points. This will lead to the duration being recalculated based on the new combo point value, which can shorten the effect by a very large amount (a 5-combo, fully talented Slice and Dice will last 30 seconds, whereas at 1 combo point it will only last 12 seconds. The remaining 18 seconds are lost).

The talent Ruthlessness gives an up to 60% chance to gain one combo point when using a finisher. If the player were for any reason to cast either of the two finishers with multiple combo points and then accidentally recast it with the single combo point given by Ruthlessness, they will end up losing valuable time on the buffs. This does not mean that the bug involves Ruthlessness, it is simply the easiest way to inadvertently replicate the bug.

**Steps to reproduce the behavior with as much detail as possible:**

1. Gather 5 combo points and cast Slice and Dice
2. Gather 1 combo point in any way and cast Slice and Dice
3. Observe the buff duration decreasing

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell: https://database.turtle-wow.org/?spell=45604
Spell: https://database.turtle-wow.org/?spell=6774

**Expected behavior. Describe how it should work:**
The longer duration effects should not be overridden. "A more powerful spell is already active" should be posted as an error message and the ability should not trigger.

**Comment by imaglcian** [comment]
this is **NOT** how the ability should work. This would impede the already dumbed down rogue class even more. You can refresh Slice and Dice whenever you wish, and overwrite your own buffs.
(Example: In raid, having 3 seconds left on Slice and Dice, and refreshing it early before a mob dies)

**Comment by RUTHINAS** [comment]
> You can refresh Slice and Dice whenever you wish, and overwrite your own buffs. If this was changed to what you are suggesting, it would impede rogue gameplay even more.

I do believe you should be able to refresh Slice and Dice whenever you wish. However, the key word here is _refresh_. I don't think the rogue should be prevented from casting Slice and Dice (or Flourish) if the duration that remains on the buff is shorter than the duration which would be gained from casting it. This means you should _always_ be able to use a 5 combo Slice and Dice, since even in the completely hypothetical scenario where you've just cast a 5 combo Slice and Dice, _at least_ one global cooldown has already passed, and the new buff would therefore be longer than what remains of the old one.

In their current state, the only thing I have an issue with when using Slice and Dice and Flourish is the fact that they lose duration. I don't mean this to be fixed by having the durations add up (as was presented in your TL;DR. In fact, I don't even mind it that much if the combo points and energy are lost if the rogue fumbles their key presses. **I'd just like for the longest of the two durations to be the one that remains.**

What I am suggesting is not "Prevent rogues from using Slice and Dice while the buff is in effect", but rather "Prevent buff duration being lost".

I don't recall how this was in Vanilla, expansions or Classic. This is, however, the first time in a rogue career of over fifteen years that I have paid attention to the existence of this bug/feature. Now, this could be because it is a Turtle-specific bug – or it could be that I have only noticed it because the way I am playing currently vastly differs from how I used to play on previous servers, namely tanking as a rogue. With the addition of Flourish (and the bug/feature being present on Flourish as well), the need to keep both Flourish and Slice and Dice active, and the constant target swaps I need to be doing as a tank I constantly face situations where I have only one or two combo points on a target, and am getting ready to swap to another to build up threat. In these situations I would need to:

1. Check buff durations for Flourish and Slice and Dice
2. Check combo points
3. Estimate whether the remaining duration is lower than what would be gained from casting the ability now
4. Decide whether to cast Flourish or Slice and Dice
5. Pick a new target

Despite tracking combo points both with visual and audio cues, and having duration bars for both abilities, it is not unheard of that I end up wasting duration from the buffs due to a miscalculation.

Besides, the issue tracker discussion linked by @imaglcian comes to this conclusion:
> Considering this, I guess there is no "A More Powerful spell is already active". **A smaller duration doesn't replace the longer duration but it eats up the combo points anyway.** (Emphasis added by me.)

**Comment by imaglcian** [comment]
This is not a turtle-specific bug, and is however an expected behavior.
With a little bias, I would like to state that the idea of a "Rogue Tank" to me has always seemed like a single-target tanking option (That's what we've gotten tools for only any how), I think your best option is to make a forum post with these suggestions, as it's currently not a bug or unintended feature. The idea of Combo Points already is a single-target thing, and rogues don't have any proper AOE. (Also something that would have to be suggested through forums)


**There would be 2 issues however with this proposal**

* Coding the client in such a way, that it checks for duration left, combo point amount and what finisher has been used, while also prioritizing to _not_ refresh if the duration would not increase would be a lot of work.
* This would also mean, that it could lead to buggy or impeding behavior, say you waste 25 energy + x amount of combo points, because the duration does not increase. (Even if it was "changed" to not do so)


**The only way to go around this (And as other rogues do), is to either do the following:**

* _Change_ how finishers work (Which again should probably be emphasized in a forum post rather than here), and make it so you do not lose 25 energy or combo points when using flourish/slice and dice of lower combo-point amounts
* What other rogues (as well as me) do, is to pool energy, which you can do up until 80 energy + 3/4th of the incoming energy tick, or 100 energy if you have not gotten any parries (Meaning you would lose 1-9 energy from the next tick) - This means you don't lose any DPS, but you rather save it to either give more space to the tanks, or to line up your finishers a bit better.

I would also want to state, that Flourish as is, is already super hard to line up properly with Slice and Dice, due to it's duration being equal to 'Slice and Dice -1 combo point', which effectively renders any proper rotation _useless_. (I have already made a big forum post regarding this and many other things)

**Comment by RUTHINAS** [comment]
> Either way, I don't agree that this should be fixed, just since it would impede every other factor of rogue gameplay (besides tanking), in regards to the examples I posted in my previous comment. (Not being able to refresh Slice and Dice with a lower-point amount, right before the mob dies, and not having to use it for the next mob pull

Reading this I think there's a misunderstanding of what I am reporting.

If I understood your message correctly, you don't believe Slice and Dice should be "fixed" so that using a lower combo point cast of it is wasted when a higher combo point cast is already running, regardless of time remaining.

This is, however, not what I am suggesting. What I mean by this report is that regardless of how many combo points it took to cast the initial buff, a buff with more duration _remaining_ should not be replaced by a shorter buff. If a 5-combo Slice and Dice has 3 seconds remaining on its timer, a 1-combo Slice and Dice _should_ replace it with its 9 second duration (untalented). Indeed, the inability to recast or refresh Slice and Dice in such a situation would seriously impede rogue gameplay, but it is not at all what I was suggesting.

Like I quoted from the previously linked issue tracker conversation in my prior message:

>A smaller duration doesn't replace the longer duration but it eats up the combo points anyway.

This would indicate that the behavior on Turtle is currently bugged.

**Comment by twowTurtReynolds** [comment]
Working as Blizzard intended.
