### ISSUE TITLE
E'ko Drops in Winterspring Are Only Lootable by a Single Character

### ISSUE THREAD

**Issue by imcdermott13** [slowtorta/turtlewow-bug-tracker#3391]
Creatures in Winterfall are only dropping E'kos for a single character within a party or raid when slain.

Many of the creatures in Winterfall will drop an E'ko item when slain for any players that have a Cache of Mau'ari. Originally every player in a party or raid would be able to obtain an E'ko whenever a creature dropped on as long as they had the Cache. This promoted sharing creature kills in the zone, since grouping up made farming them more efficient, especially when dealing with the elite Giant monsters in the Southern part of the map.

As of the last update, these E'kos are only able to be obtained by a single person in the group at a time, with no patch note or closed bug detailing why this happened.

**Steps to reproduce:**

1. Form a Party
2. Have players in the party go to Winterspring
3. Slay any of the Furbolg, Chimaera, Moonkin, Bears, Cats, Yetis, or Giants in the zone until an E'ko drops
4. Note that only a single player in the party is able to obtain the E'ko

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=12384

https://database.turtle-wow.org/?item=12430
https://database.turtle-wow.org/?item=12431
https://database.turtle-wow.org/?item=12432
https://database.turtle-wow.org/?item=12433
https://database.turtle-wow.org/?item=12434
https://database.turtle-wow.org/?item=12435
https://database.turtle-wow.org/?item=12436

**Expected behavior:**

Every member of a raid group or party that has a Cache of Mau'ari should be able to loot the E'ko whenever it drops.

**Comment by balakethelock** [comment]
That is changing blizzlike behavior for the worst

 You are recklessly making big changes that will harm the raiding community who was farming these Ekos for **itself** to use in **its own raids**, not to put them on the auction house.

If you want this to be an individually farmed consumable, then up the drop rate to at least 50% (and 100% of the giants)
Frankly this is ridiculous and awful for the long term health of raiding.

**Comment by suggney** [comment]
this is the single worst change you've made besides world buffs

this increases the time higher end raiders need to spend to get their ekos significantly

change this.

**Comment by Sanctium** [comment]
Frostmaul E'kos have a drop rate of 15%. Juju Might, when turned in, is a 40 AP buff that lasts for 10 minutes. For an ordinary 3 hour Naxx clear, a raider might expect to need to use somewhere in the realm of 20 Juju Mights. Frostmaul Giants are elite mobs which require a group to efficiently farm. Winterfall Firewater, by contrast, is a 20 minute buff for 35 AP that lasts 20 minutes and can be farmed off nonelite mobs en masse. This change punishes raiders who seek to achieve more by interacting with the world as a large group by making an already difficult consumable nearly impossible to get your hands on.

The same farm that gets Winterfall Firewater also yields Winterfall E'ko at a 15% drop rate, which converts to a 30 minute, 30 Strength buff. This consumable is much more expensive and difficult to acquire than its counterpart, Elixir of Giants, which lasts for an hour and provides 25 Strength instead of 30. By increasing the difficulty associated with farming Juju Powers, an already marginal increase in performance for a huge increase in scarcity becomes even less approachable.

Making these items more difficult to farm will make them more expensive, not less, and directs senior raiders away from world interaction and toward cheaper, lower-performing alternatives. This change was unwanted and only serves to punish a segment of the community which opts into playing more to perform better.

**Comment by Ducky-twow** [comment]
> The team decided that people making 40-man raids to kill single enemies in Winterspring for 40 E'kos to play the economy was not something that we felt was conducive to the long-term health of the server economy. It was left out of changelog by mistake.

I honestly cannot fathom the thought process behind this change. If anything I thought you guys would make more consume farms behave like ekos. Similarly to the CC badges, seeing another player doing it immediately makes you want to reach out and group with them, as doing so makes both of your lives easier. This is on the whole better for the sense of community, cooperation, etc. Instead it just becomes a frustrating game of who tags what first and everyone disliking each other for daring to want the same things. 

I also don't see how this in any way helps the economy. Demand for these items isn't going to change for this, but supply is going to be dramatically lower. So the prices will go up. We've seen you change things like Black Lotuses in the past in response to inflated AH prices, so why go the other way on this one? 

Wouldn't a better change for everyone be to make things like Tea Leaves, Firewater, Blasted Lands quest items etc. all behave like ekos so more people would be inclined to group when doing them? There's a reason why quests intended for groups like the aforementioned CC badge quests don't require you to collect quest items from mobs.

**Comment by suggney** [comment]
> > The team decided that people making 40-man raids to kill single enemies in Winterspring for 40 E'kos to play the economy was not something that we felt was conducive to the long-term health of the server economy. It was left out of changelog by mistake.
> 
> I honestly cannot fathom the thought process behind this change. If anything I thought you guys would make more consume farms behave like ekos. Similarly to the CC badges, seeing another player doing it immediately makes you want to reach out and group with them, as doing so makes both of your lives easier. This is on the whole better for the sense of community, cooperation, etc. Instead it just becomes a frustrating game of who tags what first and everyone disliking each other for daring to want the same things.
> 
> I also don't see how this in any way helps the economy. Demand for these items isn't going to change for this, but supply is going to be dramatically lower. So the prices will go up. We've seen you change things like Black Lotuses in the past in response to inflated AH prices, so why go the other way on this one?
> 
> Wouldn't a better change for everyone be to make things like Tea Leaves, Firewater, Blasted Lands quest items etc. all behave like ekos so more people would be inclined to group when doing them? There's a reason why quests intended for groups like the aforementioned CC badge quests don't require you to collect quest items from mobs.

this. it literally helps promote teamwork. this change isolates people doing boring things. it's a net fun reduction that also impacts raiders significantly. now we'll need to farm more hours for the same amount of consumes we need. please rethink this, devs. it's not smart.

**Comment by snakemansreal** [comment]
I can guarantee no raider group was farming frostmauls to play the economy. Before the nerf, it was often more efficient to farm gold and buy them from non-raiders on the auction house who were multiboxing e'ko farms, due to the giants being marked as elite and the drop rate of the item itself. This change screws over hunters in particular, as their ONLY option for an attack power consumable exists in Juju Might - Winterfall Firewater gives only melee attack power. Solo farming the giants for e'ko is wildly inefficient, as stated earlier, as the drop rate is so low that you can be there for hours killing giants to get as many e'ko as you need to last a full raid.

If the ultimate goal with removing world buffs in raid instances was to reduce the amount of time people spend farming outside of alotted raid times to clear the content, this is among the worst changes that could have been made to the game. What used to be a mostly quick n' nasty farm you did with a couple of your friends has turned into more than likely the majority of your time spent out of raid. Extending the length of time each raider spends farming these things in turn increases the chances of people having to fight for mob tags, which is already becoming enough of a problem as it is when one tries to fit several thousand concurrent users into a single vanilla world.

Please, consider reverting this change, for the health of the raiding community.

**Comment by lyssebabz** [comment]
So you remove gold sink from flamewrath leggings and add a HUUUUGE gold sink for juju might.. thank you very much

**Comment by Avery1337** [comment]
Please fix this.  This is NOT blizz-like at all and just makes this farm 1000% harder on raiders.  Jesus Christ...

**Comment by fatnerdynerd** [comment]
Unless you make it so that Ekos also have 100% drop rate THIS WILL JUST ENCOURAGE GOLD SELLERS AS THERES NO WAY PEOPLE WILL FARM THESE 1 BY 1 OR PAY 10G FOR ONE ON THE AH
FIX THIS THIS IS A HORRIBLE CHANGE

**Comment by Haaxor1689** [comment]
> I can guarantee no raider group was farming frostmauls to play the economy. Before the nerf, it was often more efficient to farm gold and buy them from non-raiders on the auction house who were multiboxing e'ko farms, due to the giants being marked as elite and the drop rate of the item itself.

See, you said it yourself. Non-raiders were exploiting this by multiboxing and selling them on AH for easy gold. Why should there be a market for that?

**Comment by suggney** [comment]
> > I can guarantee no raider group was farming frostmauls to play the economy. Before the nerf, it was often more efficient to farm gold and buy them from non-raiders on the auction house who were multiboxing e'ko farms, due to the giants being marked as elite and the drop rate of the item itself.
> 
> See, you said it yourself. Non-raiders were exploiting this by multiboxing and selling them on AH for easy gold. Why should there be a market for that?

dualboxing is allowed. the raiders who would do this and fill the market helped keep prices down, because if you're not in a big dual-box group of ten people collecting eko's to supply your raid and the server, nobody will farm them, as it sucks that bad. i encourage you to go gather a pack of five people and tell me how long it takes you to get 20 frostmaul ekos, with this current state

**Comment by suggney** [comment]
lowering the supply more than tenfold on a rare raid consume melee and hunters use a LOT of every single raid if they wish to perform at a high level significantly increases their value and cost. doing so is counterproductive to the idea of reducing the required investment in a raid (removal of world buffs allegedly saved people time). this will force people to solo farm elites at a grinding pace, running the cost of these ekos such that people who can't stand that farm have to gold farm multiple more hours to afford a batch. or, well, they'll just buy gold if it's too inconvenient.

**Comment by suggney** [comment]
> > See, you said it yourself. Non-raiders were exploiting this by multiboxing and selling them on AH for easy gold. Why should there be a market for that?
> 
> Your rules allow dualboxing and the mechanic is designed that way, calling this an exploit is a big stretch of the definition of the word.
> 
> And being a 15% drop rate, for a dual boxer they are better off doing DME or Strat or any other dual boxed farm. Such instanced farms make much more gold than this. You think it's easy gold but I can assure you it's not profitable at all.
> 
> And it really shows where your priorities lie if you think it's good to punish the whole raiding community to hurt a mediocre gold farm of dual boxers.

piggybacking off of this, haaxor, why are you ignoring every other point to single out a gold farm that isn't even as efficient as DME? are you going to go after DME farming next? it sure makes raiders a lot of gold.

**Comment by fatnerdynerd** [comment]
This is going to encourage people who STILL want to parse to just spend money on needmana to be able to buy it.

PLEASE IF YOU DON'T WANT PEOPLE TO MULTIBOX THESE MAKE THESE A FUCKING 100% DROP RATE INSTEAD OF DOING THIS FOR THE LOVE OF GOD

**Comment by NotShiggy** [comment]
Doing this without increasing the drop rate drastically will only make the consume insanely expensive and push high end players either to burnout from over farming other things (also breaking the economy even more) or push them to buy gold from goldsellers. Great job, keep it up!

**Comment by jameyboor** [comment]
Removing party loot shouldve been accompanied with an increase in drop rate. This was not done unintentionally and will be looked at and fixed.

**Comment by imaglcian** [comment]
So this was not changed by accident? #2890 
It seems to have been closed, then fixed on accident because of bad communication. 
Heck, you can't farm these on multiple characters unless you have the Cache of Ma'uri anyway, so you literally can't get a 5-man level 1 party.

**Comment by fatnerdynerd** [comment]
Zoomer read ratkosrb' comment at the top

**Comment by imaglcian** [comment]
Even so, the price of each E'ko is only inflated because of this one change. In no world would it be worth 12g for a 10-minute buff.

**Comment by suggney** [comment]
> Removing party loot shouldve been accompanied with an increase in drop rate. This was not done unintentionally and will be looked at and fixed.

thank you, and i feel like this is a good step, but please do consider more on how to make frostmaul ekos in particular more practical. you can't increase the rate enough to compensate for the price increase solo farming will cause unless multiple frostmaul ekos drop off a kill.

**Comment by Ducky-twow** [comment]
> Removing party loot shouldve been accompanied with an increase in drop rate. This was not done unintentionally and will be looked at and fixed.

This is something at least. Thank you!
But I still dislike the move away from party play and towards solo play. I understand you don't want players dualbox / multibox farming these but more things in the game that encourage party play should be encouraged. I always thought these were in a perfect place. Soloable if you need to, but grouping is preferred.

**Comment by jameyboor** [comment]
They were not just serving their intended purpose but more, hence the change. Another option would be to reintroduce party loot but keep them BoP but this would introduce other issues. For now their drop rate will be altered on next server update and loot will stay as is.

**Comment by Ducky-twow** [comment]
> They were not just serving their intended purpose but more, hence the change. Another option would be to reintroduce party loot but keep them BoP but this would introduce other issues. For now their drop rate will be altered on next update.

BoP is an interesting one, as it eliminates a good chunk of the value in dualboxing them. But it's also nice to be able to trade with friends, buy off ah when you didn't have time that week to farm etc. I think I would prefer it they were bop rather than removing the party loot, but I may be alone in that sentiment. :)

**Comment by Zebouski** [comment]
Reposting my post from the last time we discussed this:

Geojak, this fix on a blizzlike interaction would remove one of the very few goldfarms in the game that actually encourage you to group up with strangers and friends. Encouraging socialization through the game design, is one of the core tenents of vanilla wow, and going the other way, to encourage people to play solo in this mmo.... well that's super duper lame. I feel everyone else in this thread feels this same thing, they just dont know or care enough to articulate it. Hopefully this sheds some light.

There's also the fact that "bug" is something up to interpretation. Perhaps the blizzard dev who added the Eko's just reused code for quest items, where the quest item drops for all party members, and despite it not making sense, they found the boon to group goldfarming a good thing and left it in. We have no way to know, without asking that guy, what his thoughts were. The lesson here is that: Something is only a bug, only if the weird side effect is undesirable.

Yes people bringing 10 accounts multiboxing to pick them up is cringe. But that's been fixed, we're now only allowed two 2box in the world in combat.

And yes, a 40man raid farming a place would be strange, but here's the thing, there's a limited amount of eko dropping mobs to kill, each with their fixed respawn times. Even at 3 people, you will raze a winterfall village to the ground. 5 people is kind of the max, and any more trying to farm the area will just eat into eachother's profits until it is no longer any good. The problem of a 40man raid farming something solves itself, and now you see why 40mans are never seen farming winterspring.

**Comment by SabineWren** [comment]
> ...E'kos to play the economy was not something that we felt was conducive to the long-term health of the server economy.

Nobody plays WoW to solo farm raid consumes, but you changed a group activity into a crappy solo grind?

> Another option would be to reintroduce party loot but keep them BoP...

Duh. BoP is fine, but solo loot isn't.

**Comment by Avery1337** [comment]
> 
The 40 man farms are for the Giants in the gorge not in the village.

**Comment by Avery1337** [comment]
> Reposting my post from the last time we discussed this:
> 
> Geojak, this fix on a blizzlike interaction would remove one of the very few goldfarms in the game that actually encourage you to group up with strangers and friends. Encouraging socialization through the game design, is one of the core tenents of vanilla wow, and going the other way, to encourage people to play solo in this mmo.... well that's super duper lame. I feel everyone else in this thread feels this same thing, they just dont know or care enough to articulate it. Hopefully this sheds some light.
> 
> There's also the fact that "bug" is something up to interpretation. Perhaps the blizzard dev who added the Eko's just reused code for quest items, where the quest item drops for all party members, and despite it not making sense, they found the boon to group goldfarming a good thing and left it in. We have no way to know, without asking that guy, what his thoughts were. The lesson here is that: Something is only a bug, only if the weird side effect is undesirable.
> 
> Yes people bringing 10 accounts multiboxing to pick them up is cringe. But that's been fixed, we're now only allowed two 2box in the world in combat.
> 
> And yes, a 40man raid farming a place would be strange, but here's the thing, there's a limited amount of eko dropping mobs to kill, each with their fixed respawn times. Even at 3 people, you will raze a winterfall village to the ground. 5 people is kind of the max, and any more trying to farm the area will just eat into eachother's profits until it is no longer any good. The problem of a 40man raid farming something solves itself, and now you see why 40mans are never seen farming winterspring.

The 40 man raid farming were for the giants not the furbolgs.

**Comment by fatnerdynerd** [comment]
> 

theres 0, zero, nada, nill nulla people or guilds farming giant e'kos as 40 people, hence why they're so frickin expensive, sometimes guilds advertie but usually at most 10-15 people even care enough to do it. This change hurts the top 1% while granting nothing to the 99%.

**Comment by balakethelock** [comment]
A good compromise imo is:
1) if you are solo, the drop rate on e'ko is 100%
2) if you are in a group of two or more, the drop rate on e'ko is 50% for each person
3) e'kos remain tradeable

this makes it so that:
1) solo players can still effectively farm it for themselves.
2) Dual boxers will see on average 1 e'ko per kill just like a solo player.
3) Dual boxers can't bring in another character to triple-box or higher, because that's against the rules.
4) Bigger groups of friends will all be able to loot and benefit.

**Comment by snakemansreal** [comment]
> > I can guarantee no raider group was farming frostmauls to play the economy. Before the nerf, it was often more efficient to farm gold and buy them from non-raiders on the auction house who were multiboxing e'ko farms, due to the giants being marked as elite and the drop rate of the item itself.
> 
> See, you said it yourself. Non-raiders were exploiting this by multiboxing and selling them on AH for easy gold. Why should there be a market for that?

My point being that raiders shouldn't be punished for something non-raiders do. Misattributing issues with muh economy to raiders who farm stuff in groups to make it 1) faster 2) less mind-numbing to gather the consumables they need to play at a high level isn't a very good look tbh.

That aside, removing something that can be done as a social activity from turtle really goes against the grain of Vanilla's essence. If the issue truly lies with multiboxing, just fuckin ban it outright in the open world, outside of stuff like doing profession related activities/summons/portals for your alts or farming instanced content. Yeah, it'd blow; I have five accounts for a reason. But dancing around the real problems and making kneejerk changes without any community input doesn't actually help anyone playing the game. At the very least, I feel like big changes like this that heavily affect significant niches of the community should be polled and discussed rather than dropped into a weekly maintenance patch with an "oops, we forgot to tell you guys about this" note after the fact.

I am glad the drop rate is being upped, though. It's a step. <3

**Comment by Avery1337** [comment]
> 



> > The 40 man raid farming were for the giants not the furbolgs.
> 
> My response still stands. Optimal eko farming involves a mix of the drops AND the ekos. The more people added to the farm, the less GPH everyone gets.

The point of the eko farms were not for the gold.... its for raiding with full consumes the whole raid.  Naxx requires us to do this and the new raids coming will require the same things constantly.  Juju mights only last for 10 min my man.  These raids are 3 hours at least with possibly multiple wipes.  Fuck the gold bro.

**Comment by imaglcian** [comment]
I think 1 thing we're overlooking is how fucked hunters are already. You HAVE to get these because Winterfall Firewaters don't stack for Ranged AP. This has already been annoying to do. Got 15 after an hour while farming with a friend who got 9 after an hour.

**Comment by testening** [comment]
Completely nonsensical change.
NOT BLIZZLIKE.
There is NO evidence people are multiboxing several characters to farm this - and there never will be, since anyone with two 60's already had better farming options.
Heavily nerfing the supply of an essential raid commodity AFTER the server explodes in population? When people were already wasting over an hour per week just to get the bare minimum for one week's raids? Absolutely indefensible.

**Comment by redmagejoe** [comment]
Stop saying Not Blizzlike. Turtle doesn't care if it's Blizzlike or not. This isn't a Blizzlike server. Saying this change is "Not Blizzlike" immediately hurts your argument.

**Comment by snakemansreal** [comment]
> Stop saying Not Blizzlike. Turtle doesn't care if it's Blizzlike or not. This isn't a Blizzlike server. Saying this change is "Not Blizzlike" immediately hurts your argument.

I dunno, Turtle's age-old philosophy to embody the spirit of vanilla WoW while adding onto the base game sounds pretty close to "we want to be as Blizzlike as we can" to me. A lot of the class changes were ripped right from WC3 and the beta, as well as things like Survival and dishonour ranks.

**Comment by lyssebabz** [comment]
Could make is so they dont drop in a raid group and if you're grouped, they have a lower drop rate. A couple of friends could spend a long time farming there with each their own alt hauling behind. It was great for raiding. Price of Frostmail E'kos right now (before change) fluctuate between 3g and 5g, if a naxx raider uses 1 for each naxx boss that's 12x3=36g for this one consume currently for naxx raiders. I sure hope the price dosen't go much higher

**Comment by ametc1** [comment]
This is such a bad change, let people at least get them in 5 man groups but not 40 mans

**Comment by DuvelCorp** [comment]
> The team decided that people making 40-man raids to kill single enemies in Winterspring for 40 E'kos to play the economy was not something that we felt was conducive to the long-term health of the server economy. It was left out of changelog by mistake.

This one of the worst change of Turtlewow ever and the reason invoked here is absolutely ridicoulous, idiot, stupid, speechless. Devs are not playing the game.

1. We have never seen ANY 40-man people raid there. For the simple reason that being 6 or 7 well geared players is largely enough to overcome the Giant's repop  timer.
2. Stating that it hurt the economy is non sense. 
3. We are multiboxing those for 15 years and it wasn't a problem anywhere until Turtlewow decide it is finally a  problem. You restricted the multi-boxing to 2 accounts only, it was largely enough to not make it worst again.

This is a pure Naxx raider consume, especially for hunters that dont have winterfall waters. We spend a massive amount of time to farm our consumes each week and this change will make it much more complicated, for just nothing, except a dumb decision from a dumb dev.
