### ISSUE TITLE
Cone of Cold Animation Bug

### ISSUE THREAD

**Issue by Kitmit27** [slowtorta/turtlewow-bug-tracker#341]
**Please, provide a clear description what the bug is:**
When casting "Cone of Cold" on my Female High Elf, the animation of the skill is being displayed on the side/back of my character instead of the front. The mechanics of the skills seems to be working correctly, but animation is not correct.
**Steps to reproduce the behavior with as much detail as possible:**

1.  Cast Cone of Cold.

**Expected behavior. Describe how it should work:*
![CoCAnimation](https://user-images.githubusercontent.com/91370086/134767203-5da2a7c5-1587-4a6e-a115-8b6c90d07a3f.jpg)
*

**Comment by slowtorta** [comment]
Fixed in patch 1.16.1 along with: 

• Spell effects not centered properly on High Elf females: https://github.com/slowtorta/turtlewow-bug-tracker/issues/549 https://github.com/slowtorta/turtlewow-bug-tracker/issues/341
• Missing High Elf sit animation when using chairs: https://github.com/slowtorta/turtlewow-bug-tracker/issues/301
• High Elf female character is not seated in the center of a mount saddle: https://github.com/slowtorta/turtlewow-bug-tracker/issues/355
• On female high elves, when walking (and only when walking) with something equipped in the offhand, the offhand item will continually unsheathe and sheathe with the sound for said action being done as well. Happens with weapons, shields, and generic offhand items.

• When fishing, high elf model acts weird like on image: https://github.com/slowtorta/turtlewow-bug-tracker/issues/410
• High Elf long capes visual bug. It looks like ripped in half: https://github.com/slowtorta/turtlewow-bug-tracker/issues/429
• Hunter pets clipping the ground in the character select screen of High Elf characters: https://github.com/slowtorta/turtlewow-bug-tracker/issues/495
• Weird high elf upward swimming: https://github.com/slowtorta/turtlewow-bug-tracker/issues/597
• High-elf (Female) priest tier 3 helm visual effects are broken: https://github.com/slowtorta/turtlewow-bug-tracker/issues/1181
