### ISSUE TITLE
AQ40 Skeram paladin MC dmg is out of control

### ISSUE THREAD

**Issue by fatnerdynerd** [slowtorta/turtlewow-bug-tracker#3443]
**Please, provide a clear description what the bug is:**
During the boss fight, The Prophet Skeram, Paladins during mind control have a chance to deal obscenely high damage
**Steps to reproduce the behavior with as much detail as possible:**

1. Engage The Prophet Skeram and have a retribution paladin fall under mind control with Seal of Command talented
2. Once the MC'd paladin attacks another player, they take ridiculous amounts of damage.

https://media.discordapp.net/attachments/1044629927816855653/1103900309811634286/image.png

**Expected behavior. Describe how it should work:**

Paladins shouldn't deal 20000 damage to players during Mind control. Even if players gain a 300% damage increase, a spell that normally does 1000-2000 damage shouldn't do 1000% as much.

**Comment by balakethelock** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3393

The consensus reached was to best fix this, specifically target the mind control debuffs used by raid bosses and remove their double dipping on paladin damage.

**Comment by burner1024** [comment]
> The consensus reached was

It wasn't.

**Comment by burner1024** [comment]
> bruh you made a completely offtopic remark about their pvp damage. You wanna complain about that go to the forums not the bug reports github.

Do you understand the word consensus?
And you have provided 0 evidence that it's a bug at all. So who's complaining here. Bruh.

**Comment by balakethelock** [comment]
There were three people in the discussion and the three people agreed. Nobody showed up to voice their opposition despite being able to, so that's a consensus.

Your reading comprehension may be on the lower end since you're here to complain about paladins in PvP (and I'm one to agree on that, but not here. This is Github), so let me explain again what the exact problem we are reporting is:

Double dipping is not a blizzard bug;  it is unintended consequences of a custom change. When Turtle WoW added Holy Strike a completely custom spell, they didn't anticipate that enemy bosses have an interaction with Holy Strike that makes it do upwards of 10k unresistable holy damage to the paladin's allies.

The purpose of this post is to draw attention to that oversight in the hopes that they fix it. In our last KT kill, we had 3 rets and we made 2 of them respec to holy because ret paladins in a fight with mind control are a ticking time bomb. If they're not CC'd within one second, they're oneshotting somebody in melee, in a lot of cases that somebody is the tank.

**Comment by balakethelock** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3393#issuecomment-1536726182
Not a lie. The people talking about it were me, Zibouski and Geojak. You were ranting about an entirely irrelevant thing. You were not in the discussion and you still aren't, you're completely lost.

Blizzlike = works in a way consistent with the way blizzard would have made it.
Since Ignite has double dipping, this isn't a thing that was completely unknown to blizzard back in 2006. It's simply something that never manifested into a problem in practice until Turtle wow added holy strike and made ret paladins something brought commonly into raids.

Seal of command has double dipping too, paladins can use judgement or click off the buff immediately before the MC to avoid oneshotting their allies. As for holy strike, there's nothing you can do. Even holy paladins can oneshot their allies with holy strike.

Once again, this is a thread about holy strike oneshotting allies when under mind control effects.
You are not concerned with that, you are concerned about the state of paladins in pvp. So why in the world are you here talking nosense?

**Comment by burner1024** [comment]
> Seal of command has double dipping too, paladins can use judgement or click off the buff immediately before the MC to avoid oneshotting their allies.

If it's a bug with SoC, where's your proof? If it's not, then current behaviour is as blizzlike as you can say that about a custom spell.

> Once again, this is a thread about holy strike oneshotting allies when under mind control effects.

You yourself linked the other issue, where word "PVP" is literally in the first line of the description, as a resolution to this.

**Comment by balakethelock** [comment]
I literally said it's not a bug, it's an oversight.

I linked the other issue not for the original post but for the comments after it, which changed the subject from PvP to mind control effects in PvE.
