### ISSUE TITLE
Spirit Healer Stormpike Aid Station bugged

### ISSUE THREAD

**Issue by amptie** [slowtorta/turtlewow-bug-tracker#3490]
The Spirit Healer in the Stormpike AId Station is rezzing very randomly, sometimes it doesnt work 3-4 times in a row.
Then it works after about 2 minutes, but without moving the character or clicking anything.
Maybe it could be affected due to LoS problems to the NPC, since the tent is between the ghost spawn point and the Spirit Healer NPC.

1. Die at Stormpike Aid Station, while "owning" the graveyard
2. Wait for getting a rezz from Spirit Healer at Graveyard
3. Toss a coin if you are getting rezzed or not

NPC: https://database.turtle-wow.org/?npc=13116

The rezz should work every time and be reliable.

**Comment by twowTurtReynolds** [comment]
He rezzed me about 10 times, all 10 worked.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/2e0090ed-b26c-445d-9ec8-c468e452ff6b)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/8ceee5cd-62b7-46d9-8324-7cd4492b42f1)
No matter where I stand, I can't reproduce. If you can nail down the issue here on what exactly what to do, please let me know.
