### ISSUE TITLE
Gaining rested XP while glyph of exhaution is in use

### ISSUE THREAD

**Issue by SeanSmyth2** [slowtorta/turtlewow-bug-tracker#3552]
**Please, provide a clear description what the bug is:**
I created my character and purchased/consumed the glyph of exhaustion. I can see the challenge in my spellbook however when I logged in a few minutes ago I noticed I had a chunk of rested xp
![Rested XP bug](https://github.com/slowtorta/turtlewow-bug-tracker/assets/6434790/02151a60-3692-4ff1-93df-a7a4c0f8a353)

**Steps to reproduce the behavior with as much detail as possible:**

1. To my knowledge I did nothing special. I logged out in the world(Not a rested area) and came back a few hours later
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
https://database.turtle-wow.org/?item=50520

**Expected behavior. Describe how it should work:**
I expected not to receive any rested xp at any point throughout levelling

**Comment by AyleeJenn** [comment]
Yeah, I have had this numerous times for as long as I remember. However, when testing this and going troubleshooting I noticed that all the rested XP appear to vanish the moment you get your first bit of XP. Which really makes this a display bug rather than a mechanical bug since you are not getting rested XP at all and it just displays it as if you would. But you won't get it once you get a bit of experience.

At least that how it used to be. Can you confirm this by earning some experience and keeping a close eye on your XP bar to see if it behaves as I just described?

**Comment by slowtorta** [comment]
It's a visual bug, it'll go away once you do your first kill.
