### ISSUE TITLE
Curse of Tongues does not work

### ISSUE THREAD

**Issue by mikefirefly** [slowtorta/turtlewow-bug-tracker#3577]
**Please, provide a clear description what the bug is:**
It looks like Curse of Tongues doesn't work.

**Steps to reproduce the behavior with as much detail as possible:**

1. Cast CoT on target.

Expected: Target should have 50% longer spellcasting time.
Actual: Target has normal spellcasting time.

See attached video.

https://github.com/slowtorta/turtlewow-bug-tracker/assets/13250690/1eb58024-ee8c-4294-b405-7f32d18e457c

**Comment by ratkosrb** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/779fafeb-f0ed-4970-9c28-352878758df0

It does work. You can see the cast time of Fireball goes from 3.5 to 5.25 when I cast Curse of Tongues. You are relying on an addon to display a cast bar on enemies, but addons have no way to know which exact version of the spell it is, nor what modifiers are applied that affect the cast time. Have a player cast the curse on you, so that you can actually see the real cast time on the default interface cast bar that's shown only for your own character. Addons do not know the cast time of spells on other units, they just make guesses.

**Comment by mikefirefly** [comment]
Thank you for the explanation!
