### ISSUE TITLE
Blackblade of Shahram - Will of Shahram proc

### ISSUE THREAD

**Issue by Galpala** [slowtorta/turtlewow-bug-tracker#3657]
Blackblade of Shahram proc not as described, not sure if it's a bug or an earlier version of the item.

[Will of Shahram](https://www.wowhead.com/classic/spell=16598): Self +50 all stats (20 sec)

Will of Shahram supposedly can stack up to 5 times based on online testimony in wowhead, in current gameplay it can only refresh 1 stack.

**Comment by vkekd** [comment]
This is intended https://github.com/slowtorta/turtlewow-bug-tracker/issues/2532

**Comment by Zebouski** [comment]
The original issue might have been painted incorrectly because i thought at first, the +50stats was groupwide. The devs that read my post might also had not known, and said "ok thats broken nope wontfix". 

The truth is +50 stats is just self, which means this isn't cheesing tanking with +2500 stam. 

Even with jotc as is, this really warrants a fix to blizzlike.

**Comment by twowTurtReynolds** [comment]
As this sword has now been nerfed with JotC, I believe the wontfix should be lifted on this.
