### ISSUE TITLE
Mind flay audio

### ISSUE THREAD

**Issue by EstebanFailsmore** [slowtorta/turtlewow-bug-tracker#3717]
Mind flay spell rarely plays correct audio and is almost silent most of the time.

**Comment by Gurky-Turtle** [comment]
I cannot reproduce this maybe you are using the 16 sound channels client? If you are using a smaller number of sound channels in a raid some sound will not play because so much is going on. 

That or you could enable sound at the character in the sound settings but I tested a bunch of mind flays and they always make sounds. Also, make sure you are not running vanilla fixes or nampower as these can cause issues like this as well.

**Comment by EstebanFailsmore** [comment]
thanks for the reply but i already quit playing the server cause my 55
priest died to a dc.
