### ISSUE TITLE
As HC char: Buffing pvp flagged friend with Lightning Shield using Thunderhead talent will flag you for PVP

### ISSUE THREAD

**Issue by ericpierrkarvan** [slowtorta/turtlewow-bug-tracker#3722]
I got flagged for pvp with my HC shaman and the only thing I can think of is I accidentally buffed a player with Lightning Shield.

Steps:
Spec into Thunderhead and buff a pvp flagged friend with a HC shaman and get flagged.

https://database.turtle-wow.org/?spell=45508 Thunderhead.

I was using Lightning shield rank 4, https://database.turtle-wow.org/?spell=945

**Comment by sxe** [comment]
I just had the same problem, that's why I came here to report it.
I am a bit confused why this was closed. Usually you just can't cast anything on a pvp flagged player to avoid getting flagged. This is obviously super important, especially when you play hardcore. 
This is at the very least inconsistent with most(all) other spells cause as I said you simply can't buff/heal pvp flagged players but personally I would call this a bug cause it simply shouldn't be possible.
