### ISSUE TITLE
Highelf oprhan pet doesn't go into the spell book 

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#3792]
**Please, provide a clear description what the bug is:**

See 
https://github.com/slowtorta/turtlewow-bug-tracker/issues/791 

**Steps to reproduce the behavior with as much detail as possible:**

1. Start children week quest 
2. Receive the highelf orphan wistle
3. Can summon the girl but doesn't go into spellbook 
**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Expected behavior. Describe how it should work:**
All "pets" should be in spellbok
https://database.turtle-wow.org/?search=Orphan

**Comment by Gurky-Turtle** [comment]
She is a Orphan not a pet so this is intended also at the end of the quest you leave her in the care of [Aldwin Laughlin](https://database.turtle-wow.org/?npc=4974) and [Elise Laughlin](https://database.turtle-wow.org/?npc=80925)

Completion
Her mom is missing, you say? Give me a moment to look her up in our extensive collection of documents.

The girl's name is Teslinah? We do have records of her and her mother's arrival in Stormwind with the other refugees, but the two of them never showed up at the City hall for their registration.

This is a troubling discovery. We can't have people going missing in Stormwind. I will investigate, but until my investigation is completed, can I count on you to care for the girl?

Since she was registered here in Stormwind, I will issue some bonds to feed her properly.
