### ISSUE TITLE
AQ40 Anubisath Warders Use Fire Nova Too Often & Don't Use Other Abilities

### ISSUE THREAD

**Issue by Vikarec** [slowtorta/turtlewow-bug-tracker#3833]
**Please, provide a clear description what the bug is:**

There are 4 Anubisath Warders at the very end of AQ40, each in a pack with 2 Obsidian Nullifiers. 
Warders have 5 abilities:
Mass Root
Mass Silence 
Dust Cloud (-85% hit chance for everyone)
Mass Fear
Fire Nova

In TWoW they only do 2 of those randomly per Warder + fire nova. They are supposed to be capable of casting all five spells, which is consistent with vanilla reports and classic. More importantly, Fire Nova is only supposed to cast once every 15 seconds. On Turtle WoW it casts every 3-5 seconds, which is quite punishing on top of its existing repertoire and incorrect.

**Steps to reproduce the behavior with as much detail as possible:**

1. Pull a warder pack and run.
2. Watch in combat it will cast Fire Nova every few seconds infinitely until death, on top of 2 chosen extra abilities.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: 
https://database.turtle-wow.org/?npc=15311

Spell:
https://database.turtle-wow.org/?spell=26073    fire nova

https://database.turtle-wow.org/?spell=26072    dust cloud
https://database.turtle-wow.org/?spell=26071    mass root
https://database.turtle-wow.org/?spell=26070    mass fear
https://database.turtle-wow.org/?spell=26069    mass silence

**Expected behavior. Describe how it should work:**

Each warder should be capable of casting all five spells (not simultaneously), and fire nova should be casted at a much slower rate than it currently is. In classic it would cast every 15 seconds or more. Despite guilds killing the C'thun 5 mob trash packs now, most still avoid the Warder packs because of the incredibly punishing nova spam.

**Comment by balakethelock** [comment]
They can use either dust cloud or silence, not both at same time. And they can use either root or fear, not both at same time. Determined on pull, just like the Defenders use either meteor or plague.
Sources:
https://www.wowhead.com/classic/guide/trash-mobs-temple-of-ahnqiraj-strategy#qiraji-champion-packs:~:text=full%20mana%20bar.-,Anubisath%20Warder%20Abilities,-Fire%20Nova%20deals

https://wowpedia.fandom.com/wiki/Anubisath_Warder
The wiki page says in 10 may 2006, some were found that used all abilities. Since this is not mentioned anywhere else, and is not existent in classic, one can assume it's a bug that was found and fixed during 2006 vanilla before 1.12.1

As for fire nova timers, they should indeed be 15-20 secs

**Comment by Vikarec** [comment]
First result on youtube, shows a Warder using mass fear > mass silence > mass root > mass silence
Another later on uses Dust Cloud 4 times in a row instead.

https://youtu.be/0VC9GMQi4W8?t=6269

**Comment by Gurky-Turtle** [comment]
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3969

**Comment by twowTurtReynolds** [comment]
@balakethelock Do you know if your migration was adopted? If not I will poke the staff again.

**Comment by balakethelock** [comment]
> @balakethelock Do you know if your migration was adopted? If not I will poke the staff again.

It's not implemented

**Comment by ratkosrb** [comment]
It should be fixed on the next update.
https://github.com/vmangos/core/commit/dde87c6fac2f3cdcaa3de13781b04d7848633b5a
