### ISSUE TITLE
Regarding misleading bug report  "wrong droprate #3822 "

### ISSUE THREAD

**Issue by Luxsolaris** [slowtorta/turtlewow-bug-tracker#3844]
someone claimed that lashers drop is double the original blizz chance and linked wowhead as a source
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3822

the drop rate differences are not that great as they are represented in linked ticket

Lasher Root
https://database.turtle-wow.org/?item=18224
ranges from 35% to 33%
whlist
https://www.wowhead.com/classic/item=18224/lasher-root
29-27%

Thorny Vine
https://database.turtle-wow.org/?item=18222
22-20%
https://www.wowhead.com/classic/item=18222/thorny-vine
18-15%

Serrated Petal
https://database.turtle-wow.org/?item=18223
14-13%
https://www.wowhead.com/classic/item=18223/serrated-petal
12-11%
quote "Whip Lashers https://database.turtle-wow.org/?npc=13022 drops have double the chance than they should
These three items drops too often and they generate too much raw gold and it should be halved"

it is not double 

on behalf of all casual players, trying to get money for consumes, Luxsolaris, over and out

**Comment by vkekd** [comment]
if you read my bug report you will notice that im only referring to whip lashers and only that one, not the other mobs

**Comment by sarenraee** [comment]
this should not be fixed. it only generates ~40 gold an hour, while mages in ZG can make ~320. nerfing this will boost RMT and make it harder to afford raids.

**Comment by sarenraee** [comment]
other thread will have more comments on this, just to remind people to look there

**Comment by lyssebabz** [comment]
I agree with Sarenrae on this one. I spent HOURS a week for raid consumes

**Comment by turtlehead69** [comment]
> if you read my bug report you will notice that im only referring to whip lashers and only that one, not the other mobs

If you had a soul, you wouldn't do this. has nothing to do with reading. You fpos.

**Comment by vkekd** [comment]
> this should not be fixed. it only generates ~40 gold an hour, while mages in ZG can make ~320. nerfing this will boost RMT and make it harder to afford raids.

You cant vendor bijous and coins, you have to sell that in the AH and compete with other mages while DME is straight up raw gold

**Comment by Gurky-Turtle** [comment]
The other report only affects whip lashers and thats it the other lashers currently remain untouched

**Comment by afizzler** [comment]
> this should not be fixed. it only generates ~40 gold an hour, while mages in ZG can make ~320. nerfing this will boost RMT and make it harder to afford raids.

look at the AH man there's like 40 pages of bijous and coins omegalul. you think even I can compete against thousands of other players to sell?

**Comment by Gurky-Turtle** [comment]
Reverting this for now because there are a ton of conflicting values in the history of everything. Even documentation of a possible nerf in 1.10 but doesn't state if the nerf was whip lasher xp or drop rates. 

Allakhazam and Thottbot archives:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/5c5752c5-ce26-4d3a-a039-1a234301a4e5)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/8c8b532b-7f15-4980-8ce0-7ce22d784929)

What currently exists on turtle wow:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/ebd05343-6c2a-49a9-9296-5e15f6b7d715)

What currently exists on classic wow:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/90982783/7454bec1-f5dc-4acc-8052-965ba2559a05)

Blizzard Thread talking about Whip Lashers:
https://us.forums.blizzard.com/en/wow/t/lashers-insanely-nerfed/333978

Will revisit this at a later time but the values are still considered incorrect seeing they do not match other sources either so finding out the correct values will take some time. 

Closing and linking to https://github.com/slowtorta/turtlewow-bug-tracker/issues/3822
