### ISSUE TITLE
Mirage Raceway Not Working

### ISSUE THREAD

**Issue by Trixminnie** [slowtorta/turtlewow-bug-tracker#4191]
The Race in Shimmering Flats is currently not working. 

**Steps to reproduce the behavior with as much detail as possible:**

1. Once you talk to Daisy to start the race, you get stuck inside the car and the countdown doesn't begin. You are then stuck in place in the car.
2. The only way to get out of the car again is to relog. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Daisy - Race Starter Girl Display ID: 2591
Item: https://database.turtle-wow.org/?item=
Mirage Raceway: Gnome's Team, Mirage Raceway: Goblin's Team
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Normally you talk to Daisy and pick which team you want to represent, and you are then put inside of 1 of the 2 cars after a few seconds. After a few more seconds the countdown begins at 10 seconds remaining, then 5 seconds, and then it tells you to go. You are then able to accelerate and race against the other person in the opposing car.

**Comment by Deathshield** [comment]
The Prequest to test the cars before the Race in Shimmering Flats is also currently not working.

Steps to reproduce the behavior with as much detail as possible:

1. Talk to Jizzle Grikbot or Gregor Fizzwuzz to try the goblin or gnome car respectively.
2. Talk to Dolores to test the car and select either gnome or goblin team (the issue is with both cars)
3. Get placed into the car and you are unable to move, the timer never starts.
4. The only way to get out of the car is to relog.

IDs of affected creatures, items, quests or spells with a link to the relevant page:
NPCs:
Jizzle Grikbot - https://database.turtle-wow.org/?npc=50521
Gregor Fizzwuzz - https://database.turtle-wow.org/?npc=50522
Dolores - https://database.turtle-wow.org/?npc=50533
Quests:
Goblin Engineering At It's Finest - https://database.turtle-wow.org/?quest=50310
Gnomes Are Genuine Inventors - https://database.turtle-wow.org/?quest=50312
Item: N/A
Mirage Raceway: Gnome's Team, Mirage Raceway: Goblin's Team
Spell: N/A
Object: N/A

Expected behavior. Describe how it should work:
Based on what I have seen in videos on youtube; a timer should start after I talk to Dolores to test the vehicle. Once the timer has run out I should be able to move with the vehicle. The timer is not appearing and I just get stuck in place inside the vehicle. The only way to exit the vehicle is relogging. This is the same for both teams.

**Comment by SabineWren** [comment]
Able to reproduce for both gnomes and goblins.

**Comment by Trixminnie** [comment]
Now the npc Daisy has just disappeared.
