### ISSUE TITLE
Reckoning is still bugged 

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#4208]
**Please, provide a clear description what the bug is:**

The following is according #paladin. I have not tested myself. Details in linked forum post below

**Steps to reproduce the behavior with as much detail as possible:**

Sometimes you lose your stacks

**Expected behavior. Describe how it should work:**
Not lose your stacks 

Details here https://forum.turtle-wow.org/viewtopic.php?p=61169#p61169

**Comment by AyleeJenn** [comment]
Hello :)
It would help if you added the ability to your bug report. Like so ...

https://database.turtle-wow.org/?spell=20177

And since there are a number of abilities and you have not narrowed it down to the exact one that applies to you all of them need to be checked.

https://database.turtle-wow.org/?spell=20178
https://database.turtle-wow.org/?spell=20179
https://database.turtle-wow.org/?spell=20180
https://database.turtle-wow.org/?spell=20181
https://database.turtle-wow.org/?spell=20182
https://database.turtle-wow.org/?spell=45823
https://database.turtle-wow.org/?spell=45824
https://database.turtle-wow.org/?spell=45825
https://database.turtle-wow.org/?spell=45826
https://database.turtle-wow.org/?spell=45837

From what I understand of the OP's report _**spellcriticals**_ don't seem to increase the reckoning counter even though they should.

**Comment by Ironfoe** [comment]
Tested with a client with 0 addons in the installation folder.
Mounting with the Thalassian Unicorn https://database.turtle-wow.org/?item=80459 or Paladin Warhorse https://database.turtle-wow.org/?spell=13819 causes you to lose stacks of reckoning.  
Replicated by gaining a stack(s) of reckoning, mounting up, and tested both using the item/spell to demount, and right clicking buff.  From memory you should be able to mount and still reckbomb from Original Vanilla.  

I believe spell crits do give reckoning stacks, but it's been a bit since my last testing with that.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/b4bd75b4-ff64-4194-a5df-b9b67f3cb4e1)
Seems to work fine
