### ISSUE TITLE
Make tents 100% non-stackable

### ISSUE THREAD

**Issue by Jasonstotem** [slowtorta/turtlewow-bug-tracker#4214]
**Please, provide a clear description what the bug is:**
Tents are still partially stackable, and they shouldn't be. I don't know how they exactly place them one near another, but some areas of the tent can stack on each other. Today I saw the first THREE tents stacked, in this case the rested xp rate is 3x more than intended.

![Untitled](https://github.com/slowtorta/turtlewow-bug-tracker/assets/141866932/65b1b994-153d-4ceb-83a4-3959c93de9f4)

**Expected behavior. Describe how it should work:**

Tents should be 100% non-stackable.

**Comment by AyleeJenn** [comment]
Mind that what you are showing is a visual stacking. You have not given information on whether the tent EFFECT also stacks. I am saying this not to be rude but because these are two entirely separate issues. One is a 3D model issue, the other is a scripting issue.

From what it seems you are referencing a 3D model issue.

**Comment by Jasonstotem** [comment]
It's not just a visual thing, the rested xp rate also stacks, so in this case is 3x more than intended.

**Comment by slowtorta** [comment]
Fixed in the next update.
