### ISSUE TITLE
Sunnyglade valley stopped popping

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#4344]
**Please, provide a clear description what the bug is:**
Sunnyglade valley is not popping even when people queue for it.

**Steps to reproduce the behavior with as much detail as possible:**

1. Wait for sunnyglade bonus honor day
2. Survey people and see that there's a large number of players queued
3. Game still doesn't pop

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
None

**Expected behavior. Describe how it should work:**
Before, it was enough to have 5 players on each side to pop. Ever since [the July 26 change](https://forum.turtle-wow.org/viewtopic.php?p=54711&hilit=sunnyglade#p54711:~:text=Changed%20the%20player%20limit%20from%2010%20to%2020%20players.)
to make it a 20 man bg, it basically stopped popping ever.

Increasing the player cap of a bg should not increase the minimum players to enter it.

**Comment by ratkosrb** [comment]
After inflicting the torture of opening wow 20 times on my computer to queue with 10 characters per faction, I can say there is nothing wrong with the Sunnyglade queue. The battleground correctly started and invited all my characters to join once I queued with the last character.

https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/e221e65c-857b-496b-b4e1-90cb315d8456

If it doesn't start on the live server it means there are less than 10 people per side queued for it. I'll go ahead and reduce amount of people required for it to start, but the issue is lack of player interest, not the queue. For comparison the minimum player count for AV is currently 15, yet that pops without issue.
