### ISSUE TITLE
Cannot delete dead HC guildleader

### ISSUE THREAD

**Issue by 008512365** [slowtorta/turtlewow-bug-tracker#4494]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Have a hardcore guild leader
2. Have said hardcore guild leader die
3. After dying, in the character menu selection, you now cannot log in to the dead character (as it should be), but you cannot delete it either as it is the guild leader. 
4. You now have a character you cannot delete, and a guild with a dead guild leader who cannot log in and who cannot appoint a new guild leader.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Any of the following:
/gquit on HC character death,
Ability to transfer guild leader to a new lvl 1 HC char
Deleting the character in the character selection menu would force /gquit before character deletion
Allow guild leader to log in on dead character only to promote another character to guild leader and /gquit (cannot interact with world or chat with anyone)

**Comment by Frechfuchs** [comment]
Was there a solution for this already or did this only happen now for the first time, because <Still Alive> was deleted and so many HC chars created new guilds?
If the expected is not already defined I would suggest:
Guild lead automatically makes the highest guild rank (first selection, many guilds have only 1 vice guild lead) + highest level character (second selection if multiple, first in selection if multiple are the same level and highest guild rank).

Does this particular guild need a fix in retrospective too or is it disbanned already?

**Comment by 008512365** [comment]
Problem has not been solved and still need to be fixed.
At the user level there is nothing I can do, I cannot delete the character and he cannot log in to /gquit.
A GM must come in and force delete him or force /gkick him.

**Comment by slowtorta** [comment]
Please submit a ticket in game from a different character. Specify which officer must receive the leadership of your guild.
