### ISSUE TITLE
[Medivh's Merlot] doesn't stack with priest stamina

### ISSUE THREAD

**Issue by Nathan2403** [slowtorta/turtlewow-bug-tracker#4625]
[Medivh's Merlot] doesn't stack with priest stamina

1. Drink the merlot, gain hp.
2. Get Stamina buff, gain hp.
3. Click off merlot buff, hp remains the same.

Just thought I'd point this out in case it was intended to stack, since as of right now, the merlot is entirely useless.

**Comment by balakethelock** [comment]
#3994 this bug again
https://github.com/vmangos/core/blob/12908fc8f45237944571c38cf695dcd4f6d8acd4/src/game/Spells/SpellAuras.cpp#L8307
@devs: you have to add the spell id of the buff to this list
The real solution is just rewriting it completely to an opt into exclusivity system rather than opt out of exclusivity
