### ISSUE TITLE
Ornate Bloodstone Dagger still not working correctly

### ISSUE THREAD

**Issue by bebraveorbeslave** [slowtorta/turtlewow-bug-tracker#4802]
The Ornate Boodstone Dagger no longer hurts you upon equipping it and now does the intended damage-to-self proc upon successful spell hit BUT it does not do any damage-to-target when it procs. Thanks a lot for the fix attempt, but pls try again! <333

**Comment by OonaFae** [comment]
It was stated with the last fix that the damage wont be visible in the combat log until the next patch is applied. From my testing it seems like the item does damage the enemy on spellcast (you just dont get a damage number) which is expected for now.
To verify this I would recommend trying with a low rank spell for as little damage as possible so that when you lose the HP the 250 damage proc from the blade is more obvious. If you can't replicate my findings let me know and ill try again but i'm pretty sure this is just due to the damage not displaying in the combat log.

I have opened another issue regarding this weapon not working the proc items as it should if you would like to test and contribute.

https://github.com/slowtorta/turtlewow-bug-tracker/issues/4809

**Comment by 0Moon01** [comment]
Testing a fix for this currently.

**Comment by OonaFae** [comment]
Any luck so far with the fix on this one? :D

**Comment by jonsouls** [comment]
I've tested this item earlier today with a friend. and we have identified two issues.
1: The damage proc on enemies is incapable of critting. After 100 procs with 24% spellcrit, there wasn't a single instance of the effect critting.
2: Despite being registered as spells and interaction with other spell-proc related effects, On Hit items such as the Incendosaur Set  are incapable of proccing the Dagger.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/a2183339-a5f8-445d-ae71-386be3162c8b)
Looks like the item works now.

@jonsouls 
1. Please make a suggestions forum post for this proposed buff to the proc.
2. Will be tracked under https://github.com/slowtorta/turtlewow-bug-tracker/issues/5897
