### ISSUE TITLE
Thornpod cooldown not displaying after loading

### ISSUE THREAD

**Issue by LienSimen** [slowtorta/turtlewow-bug-tracker#4808]
Thornpod cooldown is not shown after being in a loading (like in or out from a battleground).

**Comment by ratkosrb** [comment]
The issue happens because the item id is too high. It uses id 80757, but in the packet SMSG_INITIAL_SPELLS where item and spell cooldowns are sent, the spell and item id are sent as an uint16, that's a 16 bit unsigned integer with a maximum value of 65535. It is impossible to make the client show the cooldowns of items with id above 65535, because the number cannot be represented with only 16 bits. The only way to fix this item would be to change it's id to a lower number.
