### ISSUE TITLE
Multiple AV issues/inconsistancies

### ISSUE THREAD

**Issue by discer** [slowtorta/turtlewow-bug-tracker#4883]
**Please, provide a clear description what the bug is:**

Important NPCS are not placed in balanced areas on the map

Horde Explosive Expert and Mine layer are located next to Iceblood GY where as the Alliance Mine layer is all the way back in the Ally base making him take longer to kill and more difficult to get to, additionally since the mine layers hit so hard and do AoE fear on beasts with dynamite (pets, druids in form) it causes chaos pulling more NPCs within the Ally base creating a more difficult push.
![AV Map](https://github.com/slowtorta/turtlewow-bug-tracker/assets/139697479/009c3175-8373-45ec-b0e8-1f4bf7b02740)

Commanders are not equally set up:

Horde Commander Louis at Tower Point tower will not leave the tower and will reset if anyone that has aggro exits the base of the tower none of the other commanders are this way they can be kited infinitely

Ally Base Commander Mortimer is mounted and patrols the Alliance Base between the towers and the bridge entrance creating a difficult NPC to kill or pass before being able to get to the towers.
Horde Base Commander Mulfort is stationary at the Horde flag meaning there is no threat of being pulled by entering the base or anywhere near the horde towers, additionally he can be pulled by the backdoor location through the ground by a ranged ability where he just runs out the back of the base and killed completely negating any threat of the base towers.

Horde Base has multiple entrances by jumping the side fence and running around the base fence avoiding 90% of the NPCs and Towers

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Database currently down will fill in when it returns

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

Be balanced or at least attempted

**Comment by twowTurtReynolds** [comment]
Balancing suggestions like these belong on the suggestions forum.

**Comment by discer** [comment]
I guess this part was just ignored?

Horde Commander Louis at Tower Point tower will not leave the tower and will reset if anyone that has aggro exits the base of the tower none of the other commanders are this way they can be kited infinitely

Also why does this get pushed to a forum suggestion when multiple other bug reports have the suggestion tag?

**Comment by twowTurtReynolds** [comment]
To be clear about our bug vs feature policy:

If the issue is a mistake of Blizzard, it will need a forum suggestion post to change, as these are often debatable feature/bugs. In this post, I am under the impression that the commander inbalance is like that in 1.5 AV.

If the issue is a mistake of TWoW, and it affects game balance, we'll need a forum suggestion post to change. In this post, the added backdoors for alliance to get into the horde base. Some could argue that it balances out the 1.12 bug of horde -> alliance base backdoor.

If the issue is a mistake of TWoW and doesn't affect balance, I'll keep it on the tracker marked as a suggestion. Perhaps the label should be renamed Custom Content Polish, to prevent this confusion?

However, I will say that if you have evidence that TWoW is not following VMaNGOS' 1.5 AV settings in regards to NPC placement, for example, or that vmangos' 1.5 AV is incorrect to how it was in 2005, then please do provide this proof. On second reading, you might have a bug case to argue with the Tower and Minelayer issues.
