### ISSUE TITLE
Emerald Sanctum last boss decurse issue

### ISSUE THREAD

**Issue by Koppaga** [slowtorta/turtlewow-bug-tracker#4915]
There is a curse debuff put on players that increase cast time. It's a green debuff, can't remember the name.

In tonight's raid I could not decurse it from myself as a mage and other members of the raid did not even see the debuff on me. It stayed on me. When the new curses came out I could decurse every single member of the raid except myself. And like I said other mages did not see the debuff on me. When I cast remove curse on myself it did not do anything. The effect was on me and my cast time was increased accordingly.

**Comment by Vikarec** [comment]
You're not paying attention. Removing that 30 second curse afflicts you with a new 2 minute curse that's unable to be removed.

**Comment by nickgreyden** [comment]
> You're not paying attention. Removing that 30 second curse afflicts you with a new 2 minute curse that's unable to be removed.

You are thinking of the wrong thing. Even if you were talking about what you are talking about, it wouldn't show up on decursive as it can't be removed. It was the same curse that is cast, not a new one. Even if it was the same curse and it did show up on decursive for the mage, it would show up for all mages, not just him. Once again, this was not the point. The point was that the curse was showing on this person who did not have that curse and no other person in the raid could tell (therefore, bug). Please pay attention to the full report.

**Comment by twowTurtReynolds** [comment]
Could you provide a video of what's going on here? We are failing to understand.

**Comment by nickgreyden** [comment]
> Could you provide a video of what's going on here? We are failing to understand.

Sadly no video exists of the issue. It has not reoccurred since. Here is a better description. 

Though the curse was removed, it continued to stay on the players UI as a debuff. It continued to be detected via a third party app (Decursive) by the affected player but not other curse removers in the raid. The effects of the curse were still active on the player and even manual removal could not remove the debuff by the affected player or another curse remover. Have not had this issue reappear. Have no idea how to reproduce the issue.

**Comment by twowTurtReynolds** [comment]
If the issue hasn't reoccured since, I think we're good here?
