### ISSUE TITLE
Deepwood Pipe doesn't do what the tooltip says it does.

### ISSUE THREAD

**Issue by lemonlim3** [slowtorta/turtlewow-bug-tracker#4919]
**Please, provide a clear description what the bug is:** Deepwood Pipe doesn't do what the tooltip says it does.

**Steps to reproduce the behavior with as much detail as possible:**

1. Farm 150 Bright Dream Shards
2. Buy Deepwood Pipe
3. Use Deepwood Pipe
4. Realize that Deepwood Pipe is not a Vanish + Stun like it reads, and does not put the user into stealth mode like it says it does, and additionally makes you run away like some invisible warlock cast death coil on you, even though the tooltip says nothing about that.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

https://database.turtle-wow.org/?item=61754

**Expected behavior. Describe how it should work:**

Based on the tooltip it should work like vanish does with an added aoe stun, enter you into stealth mode without causing you to run away and stun enemies in an aoe around you for 3 seconds. 

Right now it does not actually enter you into stealth mode, so you don't drop aggro, leave combat or anything, and it causes you to run away, making it pretty bad for 150 shards and a 1 hour cooldown.

Entering a GM ticket to get a refund of shards does not work - they refer us to enter a bug report.  If this item stays like this there is no reason I would have ever farmed for it or bought it in the first place.

**Comment by Imponent** [comment]
Not sure why this was closed. This needs to be investigated more and shouldn't be disregarded without explanation.

The pipe does apply an aura called "stealth" after 3 seconds (of losing control of your character), but the "stealth" doesn't function like any other stealth aura in the game. The trinket states it places you into "stealth" and works during combat. The only other ability in the game that functions like that and has similar language is Vanish. This trinket should at least drop aggro from mobs, especially if used at long range / behind line of sight, or have its description changed. There is also no indication that you would lose control of your character in the tooltip.

I can see the power of this trinket in PvP, but I am certain that thousands of gold pieces have been collectively wasted by PvE players due to this oversight.

**Comment by ratkosrb** [comment]
@Imponent  I had fixed it internally to do what you want, but then I was told that this was not the intended design of the item and it would be too strong, so it was reverted to how it was. The item will stay as it is, sorry!

**Comment by Imponent** [comment]
@ratkosrb Thanks for the reply. That is unfortunate. If the functionality isn't allowed to be changed, I still think the tooltip description should be changed.

This item is currently a gold trap for PvE players. I can't think of any reasonable justification for having an inaccurate description as an intended design. If it's clearer what the trinket actually does, there won't be a trap for future players to fall into, and resources won't be wasted on frustrated players asking to have their items refunded.

**Comment by twowTurtReynolds** [comment]
@Imponent agreed. I've added an internal tracker note for our itemization team to amend the description to say "and the user" for the stun, and this update would hit with next patch 1.17.1
