### ISSUE TITLE
Quest "Last of the Living Dead" fails to start

### ISSUE THREAD

**Issue by bug-brain** [slowtorta/turtlewow-bug-tracker#4942]
**Please, provide a clear description what the bug is:**
After turning in the previous quest I clicked on accept and immediately the quest failure sound played. Now the quest is neither in my log nor on the NPC.

**Steps to reproduce the behavior with as much detail as possible:**
I am not leveling another character to try this out.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61286
Quest: https://database.turtle-wow.org/?quest=40879

**Expected behavior. Describe how it should work:**
After clicking accept, the quest appears in my log.

**Comment by Muigin** [comment]
This will be resolved in a future maintenance.  The two quests erroneously had ExclusiveGroup set on them (the flag that causes one quest to close others so that you can only do 1 of the lot), which I have already resolved.  It will require a server restart to take effect.  Apologies for this mistake.
