### ISSUE TITLE
Enchant Weapon - Healing Power and Enchant Weapon - Spell Power enchants have two spaces between words in the enchant name

### ISSUE THREAD

**Issue by patrycos** [slowtorta/turtlewow-bug-tracker#5100]
**Please, provide a clear description what the bug is:**
Enchant Weapon - Healing Power and Enchant Weapon - Spell Power have two spaces between "Enchant" and "Weapon", causing them not to be displayed among other weapon enchants.
![enchant__weapon](https://github.com/slowtorta/turtlewow-bug-tracker/assets/51199756/5aa7d3ff-b56e-4d0d-b3af-bdc9dcfdf22c)

**Steps to reproduce the behavior with as much detail as possible:**

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Enchant Weapon - Spell Power: https://database.turtle-wow.org/?spell=22749
Enchant Weapon - Healing Power: https://database.turtle-wow.org/?spell=22750

**Expected behavior. Describe how it should work:**
There should only be one space between each word in the enchants' names.

**Comment by ratkosrb** [comment]
Spell names are client side. We have not released a new client patch. It is closed because the name has been corrected internally. When a new MPQ patch is released for the client it will contain the fixed name. It cannot be changed without a client patch, the client reads the names from its own files, not from the server.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/ab50fd7a-b076-4c64-8ffb-e658a48a0105)
