### ISSUE TITLE
Quest [Thandol Span] for Scarlet attunement chain is not doable right now

### ISSUE THREAD

**Issue by greendam** [slowtorta/turtlewow-bug-tracker#5135]
The quest [Thandol Span] requires you bring NPC Vladeus Springriver back to Menethil, however the bridge and most Wetlands are on two different layers and once you left the Thandol Span into Wetlands, the NPC disappears.

**Steps to reproduce the behavior with as much detail as possible:**

1. Have the quest [Thandol Span]
2. Go to Thandol Span
3. Defeat spawned mobs
4. Talk to Vladeus Springriver to make him follow you
5. Run back into Wetlands
6. Layer changes and NPC gone

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=50676
Quest: https://database.turtle-wow.org/?quest=80703

**Expected behavior. Describe how it should work:**
You should be able to bring the NPC all the way back to Menethil Harbor and complete the quest objective

**Comment by Muigin** [comment]
Pushing this issue to our primary Layering / Instantiating Dev.

**Comment by twowTurtReynolds** [comment]
Thank you for the report. This issue is a side effect of the Continents.Instanciate server feature that Turtle has started using around August. I'll be closing this thread and all other duplicates, but I've attached these issue to the master issue https://github.com/slowtorta/turtlewow-bug-tracker/issues/5312 that we will be using to document the many different ways this same type of issue can crop up. If you do find further cases of this bug, please do leave a comment there on the open master thread so that our dev team can use them as test cases.
