### ISSUE TITLE
Stagwood Grasp does not appear to heal. 

### ISSUE THREAD

**Issue by telostraka** [slowtorta/turtlewow-bug-tracker#5147]
1. Equip Stagwood Grasp
2. Lower your health, attack targets.
3. Check combat log and damage meters set to record healing to see no healing. 

Stagwood Grasp: https://database.turtle-wow.org/?item=61755

Expected behaviour is that Stagwood grasp should return 1% of damage dealt as healing.

**Comment by ratkosrb** [comment]
Vampirism healing is not shown in combat log. It would cause lag in raids otherwise. I tested the item with buffed stats on myself, so that I can hit for a large amount of damage to make the healing obvious. Please observe how my health immediately increases upon hitting the target.


https://github.com/slowtorta/turtlewow-bug-tracker/assets/35845488/7e7dd149-fb1f-43db-9564-f83fe32d8c96
