### ISSUE TITLE
A disappearing Mithril

### ISSUE THREAD

**Issue by Trovich** [slowtorta/turtlewow-bug-tracker#5179]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Mithril Deposit disappears while reaching it.
2. Western Plaguelands, south of Andorhal
3. 38.4/82/9

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by AchyllesTurtleWoW** [comment]
Probably the same issue like the Copper Ore Vein leaving Razorhill to the west. right behind the 2nd bristleback Camp in the southwest. 
I guess u get phased into another zone when reaching the Vein. Changing to a phase that doesnt include the vein.

**Comment by Trovich** [comment]
In my case, my location remains unchanged.

**Comment by twowTurtReynolds** [comment]
Thank you for the report. This issue is a side effect of the Continents.Instanciate server feature that Turtle has started using around August. I'll be closing this thread and all other duplicates, but I've attached these issue to the master issue https://github.com/slowtorta/turtlewow-bug-tracker/issues/5312 that we will be using to document the many different ways this same type of issue can crop up. If you do find further cases of this bug, please do leave a comment there on the open master thread so that our dev team can use them as test cases.
