### ISSUE TITLE
Vanishing! Copper Vein 

### ISSUE THREAD

**Issue by JustLord13** [slowtorta/turtlewow-bug-tracker#5212]
Vanishing Copper Vein 

**Steps to reproduce the behavior with as much detail as possible:**

1. Stay at 42.6, 51.2 at Durotar at look to south with mining profession.
2. Move to Copper Vein at 42.7, 51.2.
3. It's disappear, you are great.

https://database.turtle-wow.org/?object=1731
[https://www.veed.io/view/73b6861d-2e89-43c2-88b9-c73181fe6ca1?panel=share](url) Video of bug

It's should be digged before disappear.

**Comment by AkalixFrost** [comment]
Node should be deleted, this is occurring due to the segmentation of the world.

**Comment by AchyllesTurtleWoW** [comment]
the "you are great" is toxic af ngl

**Comment by twowTurtReynolds** [comment]
Thank you for the report. This issue is a side effect of the Continents.Instanciate server feature that Turtle has started using around August. I'll be closing this thread and all other duplicates, but I've attached these issue to the master issue https://github.com/slowtorta/turtlewow-bug-tracker/issues/5312 that we will be using to document the many different ways this same type of issue can crop up. If you do find further cases of this bug, please do leave a comment there on the open master thread so that our dev team can use them as test cases.
