### ISSUE TITLE
Ahn'Qiraj boss Emperor Vek'nilash too many thrash attacks

### ISSUE THREAD

**Issue by guzhaohui** [slowtorta/turtlewow-bug-tracker#5245]
Dear turtleWOW  GM：
   In the dungeon of the team Temple of Ahn'Qiraj, when the tank data meets the standards, the Emperor Vek'nilash causes heavy damage to the tank in one second while also making three ordinary attacks. I think this phenomenon is abnormal. Could it be a certain bug? I hope GM can investigate and solve the problem. Thank you. Dungeon ID: 12879

**Comment by twowTurtReynolds** [comment]
Testing on the PTR, letting him just wack me:

Vek'nilash seems to doublehit most but not all of his hits. He uses unbalancing stike and uppercut, and every minute or two these two abilities can end up being used in the same second, with the followup attack (or two), this can result in 6 attacks in 2 seconds with up to 3 of them with a high crushing chance due to unbalancing debuff. I didn't see any triple attacks, but regardless...

This boss is brutal right now compared to classic: https://youtu.be/ECf01WoH7rQ?t=116 where double hits are rare, and indeed he never uses uppercut and unbalancing back to back.

https://github.com/slowtorta/turtlewow-bug-tracker/issues/3444 is to track the unbalancing + uppercut issue. https://github.com/slowtorta/turtlewow-bug-tracker/issues/5245 is to track the doublehit rate possibly being too high.
