### ISSUE TITLE
Weird Phasing at Uldaman

### ISSUE THREAD

**Issue by Kharkov72** [slowtorta/turtlewow-bug-tracker#5304]
The phasing at uldaman is "fine", but it's also affecting the angor digsite pretty heavily, and of course the usual round of herbs that can never be reached before loading into another phase. phasing needs tweaked.

**Comment by twowTurtReynolds** [comment]
Thank you for the report. This issue is a side effect of the Continents.Instanciate server feature that Turtle has started using around August. I'll be closing this thread and all other duplicates, but I've attached these issue to the master issue https://github.com/slowtorta/turtlewow-bug-tracker/issues/5312 that we will be using to document the many different ways this same type of issue can crop up. If you do find further cases of this bug, please do leave a comment there on the open master thread so that our dev team can use them as test cases.
