### ISSUE TITLE
VOID ZONE

### ISSUE THREAD

**Issue by imKevinFlynn** [slowtorta/turtlewow-bug-tracker#5305]
**Please, provide a clear description what the bug is:**

Hi ! There is void zone when u come close to herbs and far away from the mobs they are dissapears it happens in the 
water and at land too. Its location in Wetlands, Coordinates is 32.4, 13.7. I tried to clear my WTB folder and also different clients (original client and my primary client with fixes that im using) it doesnt help.

![void_zone1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/109181298/1122385d-afdc-4004-88f7-6582caaa8f77)
![void_zone2](https://github.com/slowtorta/turtlewow-bug-tracker/assets/109181298/c4cac437-f1c3-4eab-b485-416aed18e8d1)

**Comment by twowTurtReynolds** [comment]
Thank you for the report. This issue is a side effect of the Continents.Instanciate server feature that Turtle has started using around August. I'll be closing this thread and all other duplicates, but I've attached these issue to the master issue https://github.com/slowtorta/turtlewow-bug-tracker/issues/5312 that we will be using to document the many different ways this same type of issue can crop up. If you do find further cases of this bug, please do leave a comment there on the open master thread so that our dev team can use them as test cases.
