### ISSUE TITLE
Quest Bug?

### ISSUE THREAD

**Issue by Feiting2** [slowtorta/turtlewow-bug-tracker#5377]
**Please, provide a clear description what the bug is:**
Can't Deliver the Quest "Anathion's Strange Request"

**Steps to reproduce the behavior with as much detail as possible:**
I have all the materials. I can see the quest giver. I have deleted the WDB folder. I talked to a GM and he requested i submit here.
I can't press continue in the quest 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Quest: https://database.turtle-wow.org/?quest=8947

**Expected behavior. Describe how it should work:**

**Comment by Aubsssss** [comment]
Please, provide a clear description what the bug is:
Encountered the same issue with 'The Isle of Dread!' (https://database.turtle-wow.org/?quest=8585).
Cannot deliver the quest to Dirge Quikcleave (https://database.turtle-wow.org/?npc=8125). Required items are in my inventory: 
1x Lakmaeran's Carcass: https://database.turtle-wow.org/?item=21027
20x Chimaerok tenderloin: https://database.turtle-wow.org/?item=21024

Steps to reproduce behavior:
Collect 1x Lakmaeran's Carcass and 20x Chimaerok tenderloin. Talk to Dirge Quikcleave (https://database.turtle-wow.org/?npc=8125). Quest mark appears gray above NPC. Quest cannot be turned in, but quest objectives are shown as completed in quest log.

Deleted WDB a few times, but that did not help. GM suggested to submit a bug report, though a guild member was able to submit the quest without issues a few minutes after me.

IDs of affected creatures, items, quests or spells with a link to the relevant page:
Dirge Quikcleave: https://database.turtle-wow.org/?npc=8125
Quest: https://database.turtle-wow.org/?quest=8585
Items: https://database.turtle-wow.org/?item=21027 ; https://database.turtle-wow.org/?item=21024

Expected behavior: quest icon should be yellow as quest objectives are completed. It should be possible to turn the quest in for the reward.

**Comment by twowTurtReynolds** [comment]
Please see https://github.com/slowtorta/turtlewow-bug-tracker/issues/6042
