### ISSUE TITLE
I was killed by the Horde in Stormwind City without PvP enabled in the Single Life mode.

### ISSUE THREAD

**Issue by zhanmuspp** [slowtorta/turtlewow-bug-tracker#5595]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.I was killed by the Horde in Stormwind City without PvP enabled in the Single Life mode.I didn't attack him first.
![WoWScrnShot_121423_084036](https://github.com/slowtorta/turtlewow-bug-tracker/assets/153786268/286cdb61-ada9-455a-b1d2-ee7910096986)

2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
PVP flags do not require you to attack enemy players nor their pets first.

They can be triggered by buffing other players, and by certain quests.

Since you are lv 30, you likely had just done the quest https://database.turtle-wow.org/?quest=1447 which DOES pvp flag you:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/3613fd9b-4906-4986-ac2c-73f67332983b)

And an enemy player found you in the 5 minutes before the flag disappeared.

We are tracking this known issue under https://github.com/slowtorta/turtlewow-bug-tracker/issues/4111 .

As always, your character will not be restored.
