### ISSUE TITLE
Mobs *appear* to spin when stunned, making "in front" and "behind" false

### ISSUE THREAD

**Issue by rptb1** [slowtorta/turtlewow-bug-tracker#562]
**Please, provide a clear description what the bug is:**
When a mob is stunned it visually turns to a random angle, but only visually. The "in front" and "behind" arcs do not change.  This means that abilities like Gouge and Backstab make no sense in relation to the mob model.

Observe the second Gouge and following Backstab in this demo: https://www.youtube.com/watch?v=DRVoVbpUrnk

**Steps to reproduce the behavior with as much detail as possible:**

1. Make a rogue and get Gouge and Backstab.
2. Apply Gouge.  Mob often spins to random angle.
3. Attempt to apply Backstab "behind" the visual model of the mob.  Often fails.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: all
Spell: https://database.turtle-wow.org/?spell=1776

**Expected behavior. Describe how it should work:**
The visual model of the mob always faces the same direction as the logical facing.

I do not remember this spinning behaviour in vanilla or on other pservers.  It may have been added to make stuns more visually obvious, perhaps?

**Comment by rptb1** [comment]
I also noticed this happening when mobs cast certain spells, such as heals, making it hard to judge moves during their casts.  Again, I do not remember this from any other server.

**Comment by geojak** [comment]
I think I remember that this behaviour was already there on nostalrius.

**Comment by Francesq** [comment]
This behavior was on Nostalgeek (French server) before core update and then have been fixed by changing the core.

**Comment by redmagejoe** [comment]
This is still an issue on Turtle. May need a tweaked fix from vmangos core if it's working properly there.

**Comment by ratkosrb** [comment]
It is working correctly on vmangos, and it is working correctly here, from the point of view of what is blizzlike.

https://github.com/vmangos/core/issues/1199

The client makes creatures always face their victim, unless they are stunned or currently moving. When the creature chases you and reaches you, it wont move again until you are out of its range. If you simply move around the npc, but not far enough that it can't reach you, the server does not need to send any movement updates for the creatures The client will automatically make it face you. But when you stun it, it now reveals the true orientation of the creature from the client's perspective. The last orientation update it received is when the creature first reached you. So if you moved somewhere around the creature since then, it will appear to turn, because that's the last orientation the client knows about. But server side the creature's orientation is constantly being updated to face its victim. So you get this mismatch between where you see it facing, and where its actually facing when it's stunned. This is a blizzlike issue that happened on blizzard's servers too.
