### ISSUE TITLE
Quest Object: Looping Animation

### ISSUE THREAD

**Issue by viiuan** [slowtorta/turtlewow-bug-tracker#5711]
**Please, provide a clear description what the bug is:**
Animation on quest-related world object loops indefinitely
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/63260365/f6461c9f-9f61-4455-be73-152f402fb8c0)

**Steps to reproduce the behavior with as much detail as possible:**
unsure if consistently reproduceable. likely happened as a result of someone interacting with the object, I did not notice it happening earlier when I personally did, only when I came upon it again at another time

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Quest: https://database.turtle-wow.org/?quest=299
Object: https://database.turtle-wow.org/?object=35252

**Expected behavior. Describe how it should work:**
animation should only play once when a player finishes the "opening" interaction

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/bd4a46a3-7172-42d3-abbe-9621865584aa)
I wasn't able to reproduce. This also sounds to me like a client bug that happened back in 2006, in which case we can't fix it.

If you are able to find out solid replication steps, please reply here, otherwise thanks for the attention to detail but I will have to close this ticket.
