### ISSUE TITLE
Our team encountered a bug on the 2nd BOSS of the Temple of Angela

### ISSUE THREAD

**Issue by Arden426** [slowtorta/turtlewow-bug-tracker#5768]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.Angel Temple # 2 BOSS: Lord Kerry, Princess Yalki, Vim. After our team killed them, the boss's body disappeared. Our team did not receive any equipment and dropped it. dungeon ID: 42921
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/32d4c5e7-59f2-4305-af85-24dd0219b8e5)
Seems to work fine, the body is not dissapearing.

Unless you can provide exact replication steps on how to replicate this issue, there's nothing we can do.

**Comment by yebingfen** [comment]
My team killed the BUG TRIO in TAQ, and finally killed Lord kri, but after killing Lord kri, his body disappeared.
This BUG occurred around 25.12.2023 14:55 server time, and caused us con't loot his drop item, waiting for your reply.
**The body is disappeared! The body is disappeared!**
server : Nordanaar  dungeon ID: 1963
Because Lord kri's body disappeared, we did not see the drop table and could not loot his drop items, please inform us of the drop and issue this drop
