### ISSUE TITLE
Hunter Class quest in Tirisfal Glades doesn't give you Training Lesson.

### ISSUE THREAD

**Issue by NullS3ct0r** [slowtorta/turtlewow-bug-tracker#584]
**Please, provide a clear description what the bug is:**
After finishing Hunter class quest chain in Tirisfal Glades, player will not recieve Tame Beast, Feed Pet, Beast Training and Revive Pet spells.
**Steps to reproduce the behavior with as much detail as possible:**

1.Get through class quests.
2. Finish the last quest in UC where is Training Lesson listed as a reward.
3. Get nothing.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
Well... You should get the Training Lesson.

**Comment by cygnus-xr1** [comment]
This problem exists on the Human Hunter quest "Training the Beast".

It sends you to Ironforge to talk to the pet trainer there [Belia Thundergranite](https://www.wowhead.com/classic/npc=10090/belia-thundergranite) , but you can't actually finish the quest at the NPC.

Theres no option for it when you open the NPC dialogue window.

I figured its because when u get the quest at Goldshire, it should send you in the Stormwind Park, then after you accept the quest its the other one which sends you to Ironforge.

![Untitled1](https://github.com/slowtorta/turtlewow-bug-tracker/assets/91410790/a6ef10a4-9c91-4b2e-b86c-9cb56b2f0c06)
![Untitled2](https://github.com/slowtorta/turtlewow-bug-tracker/assets/91410790/50efcbc5-b6e8-4d44-a6a5-524d835406ef)
