### ISSUE TITLE
Talent Spirit Armor does not work correctly

### ISSUE THREAD

**Issue by Junka00** [slowtorta/turtlewow-bug-tracker#5881]
The talent "Sprit Armor" on the Shaman Enhancement talent seems to be broken (maybe "Ancestral Guardian" too), I currently have the talents "Ancestral Guardian" (5/5) and "Spirit Armor" (3/3) and according to the talent my shield should have +40% armor (or +43% armor depends on how it is calculated) but in game I only get +10% armor on my shield.

IDs of affected spells with a link to the relevant page:

"Sprit Armor" (1/3, 2/3 and 3/3)
Spell: https://database.turtle-wow.org/?spell=45951
Spell: https://database.turtle-wow.org/?spell=45952
Spell: https://database.turtle-wow.org/?spell=45953

"Ancestral" Guardian (5/5)
Spell: https://database.turtle-wow.org/?spell=45549

I should get +40% Armor on my shield, 30% from "Spirit Armor" and 10% from "Ancestral Guardian".

**Comment by cyaohiri** [comment]
See this comment and try doing what it says, then report back. https://github.com/slowtorta/turtlewow-bug-tracker/issues/1796#issuecomment-1205056637

**Comment by twowTurtReynolds** [comment]
Turns out, Cyao is right, you are miscalculating due to that visual bug.

To be 100% clear for you and for future reference:

Base 60 shaman stats:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/781ed725-6845-4c17-935d-38344bba60bd)
With test shield, Face of Death:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/417732d6-b9c4-4f97-aaea-94444ef47275)
With 5/5 Ancestral, the math checks out, 3494 * 110% + 104 = 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/10712661-4ee4-47bf-a5c7-48b80b29d704)
With 3/3 Spirit, the math checks out, 3494 * 130% + 104 = 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/61bcf45a-14b6-4e90-830b-eff4e4e1efa1)
With both, the math checks out, 3494 * (100% + 30% + 10%) + 104 =
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/5b099072-7cee-40ca-9aca-29ecbc051e2a)


Now, I will remove the shield, and I will see bug #1796 : 
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/1bb50088-ee2e-4d7d-b303-a3f0e70b9452)

And then I relog, and that visual bug disappears.
