### ISSUE TITLE
Jailbreak quest not starting when I do it with a group

### ISSUE THREAD

**Issue by DuceAlexander** [slowtorta/turtlewow-bug-tracker#6023]
**Please, provide a clear description what the bug is:**
When I go to Marshall Windsor within Blackrock Depths to begin the Jailbreak quest it's told me twice I "Do not meet the requirements" when he has the ! above his head.
**Steps to reproduce the behavior with as much detail as possible:**

1.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by ratkosrb** [comment]
Are you Horde? This is an Alliance only quest.

**Comment by DuceAlexander** [comment]
No, the Alliance version to free Windsor.

**Comment by twowTurtReynolds** [comment]
I tested this recently and it works. It is likely that you are doing something wrong. I assume that you are letting someone else start the quest ,and are expecting it to pop up with the "Would you also like to start it" selection. Instead, what happens when you try to start it? Please take pictures.
