### ISSUE TITLE
Zandalar Signet of Migh aint applying

### ISSUE THREAD

**Issue by LRotautas** [slowtorta/turtlewow-bug-tracker#6038]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. Hey, had problems with ZG enchants before, but now i have trouble with "Zandalar Signet of Might"
2. Trying to apply that enchant via trade box (same as Nr-Fire res and other enchants) and getting message "You can only use this on an object you own"
3.  Gm told like always open a ticket here and hope for help

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=20077
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by Dragunovi** [comment]
Zul'gurub enchants are designed to be only applied to yourself in vanilla design and unlikely to change, this is the case for class enchants to prevent classes from using the enchants of different classes than their own, as for shoulder enchants its this way due to the fact you require exalted reputation to acquire them, allowing them to be applied to other people via the trade window would highly devalue the reputation itself. In short terms, this is blizzlike behavior and unlikely to change.

**Comment by LRotautas** [comment]
So gold is wasted and its over?
