### ISSUE TITLE
High Elf Hair Bug

### ISSUE THREAD

**Issue by Shoahd** [slowtorta/turtlewow-bug-tracker#6100]
1. Noticed after update my character's hair was a different color than what it was created with
2.  Bought multiple dyes, none match, and two produce the same color "Ash Blonde" and "Sunflower Blonde"
3.  This is the current color of my character's hair (Incorrect Blonde Hair Color)
![Untitled_5](https://github.com/slowtorta/turtlewow-bug-tracker/assets/157737462/d924d69f-110b-42e0-ab59-777ad2b50b90)
4.  Attempt to create a new character with the correct hair color (Grey Hair color from before update)
![Untitled](https://github.com/slowtorta/turtlewow-bug-tracker/assets/157737462/429b94a3-04ec-4eb1-b3ce-c41a104e1697)
5.  Change the Facial Hair to match my main characters facial hair and the Grey color changes to the blonde
![Untitled_2](https://github.com/slowtorta/turtlewow-bug-tracker/assets/157737462/04da149e-2668-4714-bddc-cbc4e32d2dc7)
6. I change the color back to grey manually (two clicks right for some reason, the first click doesn't change the color at all)
![Untitled_3](https://github.com/slowtorta/turtlewow-bug-tracker/assets/157737462/c47a3065-8be9-4bc7-a72e-cd51cf96182a)
7. I "Accept" the character and as the character is created the hair turns back to blonde
![Untitled_4](https://github.com/slowtorta/turtlewow-bug-tracker/assets/157737462/85182dfa-7418-41a6-9606-cfbb3bbb8d2f)

Have cleared WDB folder to no avail.

**Comment by Shoahd** [comment]
I received an appearance change token, but as seen above, I cannot change my appearance to the desired look because it reverts to blonde hair once the new character has been made.

**Comment by twowTurtReynolds** [comment]
Ah, re-reading I see the problem now and can replicate it. Thanks for the link to that earlier report which was so un fleshed out that I had forgotten about it.
Character Create Screen:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e57fd586-03ba-4939-a020-d2d3844e9522)
Once created:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/cf930924-1ae6-4381-82d2-377f4e363465)

We have found the typo in the client, and this will be fixed for everyone once 1.17.2 releases. However, so that you don't have to wait that long, you can download this patch instead which just fixes this issue:
[Patch-6.mpq.zip](https://github.com/slowtorta/turtlewow-bug-tracker/files/14057961/Patch-6.mpq.zip)
Make sure to unzip this patch and install it into your TurtleWoW/Data folder. 

The same character from above, now with the patch installed:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/abe1f804-5e8d-44de-9e60-f837c5e3f2c8)

This unfortunately does mean that others will not see you correctly as you see yourself, until 1.17.2 releases.

**Comment by Shoahd** [comment]
Yes!  I'm glad you were able to reproduce the issue!
