### ISSUE TITLE
The quest Writ of Safe Passage doesn't seem to work

### ISSUE THREAD

**Issue by Lichbanez** [slowtorta/turtlewow-bug-tracker#6141]
I camped the starting point a lot during the last couple of days and I never seen Guard Didier spawn

NPC: https://database.turtle-wow.org/?npc=16226
Quest: https://database.turtle-wow.org/?quest=9165

He should spawn twice a day at regular intervals and start some kind of escort mission but on Nordanaar he's nowhere to be found.

**Comment by ratkosrb** [comment]
I'm working on scripting this quest.

**Comment by ratkosrb** [comment]
A friend of mine researched this quest thoroughly on the official classic servers a year ago. I recreated it based on his data.

Guard Didier has a 4 hour respawn time. He starts moving together with his 5 Caravan Mules as soon as he spawns. He has a hidden aura, that causes him to aggro all enemy creatures in a 100 yard radius, making it a very difficult quest to complete. Not only do you have to be there when he spawns, because otherwise he will just die and you'll have to wait 4 more hours, but you basically need a full party to do the quest, due to the gigantic amount of mobs he aggroes on his way. If any of his mules die, he will cry (literally) and then despawn. You must protect them all to finish the escort. You do not accept the quest when he spawns, the quest becomes available after he reaches his destination. At which point you have to wait for Field Marshal Chambers to arrive and talk to him to complete the quest.

**Comment by Lichbanez** [comment]
Thanks, knowing it's once every 4 hours helps a lot.

**Comment by Lichbanez** [comment]
Chambers doesn't sign the Writ so it's impossible to turn the quest in.

**Comment by ratkosrb** [comment]
Seems like the gossip text was missing from the turtle db. It was already there in vmangos so I didn't think to include it in the migration. Should be fixed next week.

**Comment by Lichbanez** [comment]
I don't think the timing is correct, I went there to check the fix and after about 3 hours the escort started but he got killed by the patrolling elites. I returned a bit before the alleged 4 hours and not even the mules spawned back.
