### ISSUE TITLE
Return to Kheyna - quest

### ISSUE THREAD

**Issue by StasyaLyova** [slowtorta/turtlewow-bug-tracker#6204]
**Please, provide a clear description what the bug is:**
Same trouble as this, not fixed still:
https://github.com/slowtorta/turtlewow-bug-tracker/issues/1237
https://github.com/slowtorta/turtlewow-bug-tracker/issues/3447

**Expected behavior:**
As this issues closed with mark "completed" it should be possible complete Return to Kheyna. But it not fixed - even if u have this quest it have id of Return to Sven when you trying to share it. And npc not active.

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/c8d4858b-e222-4b23-95c7-872be0449269)
It looks like this was perhaps a dialogue issue? That it was meant for you to return to Chromie and not Kheyna.

**Comment by Muigin** [comment]
This quest is working as intended. This is a typical intentional (for narrative purposes) misdirection of the player by sending them to the last place they spoke to the NPC, only for the NPC to be dead, or for another NPC to take their place, or some unforeseen event to happen.

This is only a problem if you cannot turn in the quest, regardless if the Objective says to "Return to X" and you instead "Return to Y".  You can clearly see in the quest description that Chromie is explaining that they have intercepted your attempts to speak to Kheyna, who is working for a malicious party.

**Comment by StasyaLyova** [comment]
Then why when it sharing it sharing Return to Sven? 

> This quest is working as intended. This is a typical intentional (for narrative purposes) misdirection of the player by sending them to the last place they spoke to the NPC, only for the NPC to be dead, or for another NPC to take their place, or some unforeseen event to happen.
> 
> This is only a problem if you cannot turn in the quest, regardless if the Objective says to "Return to X" and you instead "Return to Y". You can clearly see in the quest description that Chromie is explaining that they have intercepted your attempts to speak to Kheyna, who is working for a malicious party.
