### ISSUE TITLE
My account has just been unblocked, and the mailbox is empty. But others cannot send me anything, because the mailbox is full.

### ISSUE THREAD

**Issue by 22d1** [slowtorta/turtlewow-bug-tracker#6251]
Hello, I am a player of Turtle Warcraft Asia Server, server: Ravenshire, ID: 疯狂面具 (Level 60, pygmy warrior). For some reasons, my account was banned for a month, and yesterday my account was released. After the launch, everything in my mailbox disappeared, and the mailbox was empty, but when I used other accounts to mail items to this account, it showed that the mailbox of this account was full and could not be mailed any things, please help me solve this problem，thanks

**Comment by twowTurtReynolds** [comment]
Mailbox contents do not last longer than a month. Please contact support.

**Comment by schanzee** [comment]
Possible explanation:
If you keep mail in your inbox for longer than than 30 days without looking inside it is returned to the sender (from whose mailbox it will permanently deleted if he also doesn't open it for another 30 days).
If you DO look inside (but do not loot it) the timer will go down to 3 days. After which the mail will disappear from your inbox but is not returned to the sender until the full 30 days have passed.
I've previously thought I had lost mail this way after sending it between bank alts because it wasn't present in either mailbox only to miraculously reappear in the sender inbox after the 30 days after original sending had passed.

That might mean the mail is invisible in the recipients mailbox but still taking up slots counting toward the inbox limit.
Now if this is blizzlike or not I do not know.
