### ISSUE TITLE
died while afk in hardcore mode

### ISSUE THREAD

**Issue by Fugger22** [slowtorta/turtlewow-bug-tracker#6259]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.i sat down at the spot in the screenshot
2. went away from the pc for a few minutes 
3. came back to find myself dead

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
https://imgur.com/a/A3s8O0d

**Comment by twowTurtReynolds** [comment]
I can only assume that this was a death to drowning, which is one of the few things that can cause that message. I'm in the area where you were, on the PTR, and I can't find any other explanation, nor can I replicate the drowning on the bridge. If you can provide solid replication steps that kills a character here, then we can investigate further into a bug, but otherwise...

**Comment by Fugger22** [comment]
i sat in the in the same spot with the same character for a solid hour and nothing of the sort happened

**Comment by Fugger22** [comment]
my headstone would have been in the body of water if i drowned
