### ISSUE TITLE
Herbs and mobs appear and disappear all the time randomly. Not all, just some

### ISSUE THREAD

**Issue by Andersph123** [slowtorta/turtlewow-bug-tracker#6349]
<img width="1280" alt="Screenshot 2024-02-23 232540" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/161089026/5f3d92d2-9875-4144-8c6c-a35be59880c0">
<img width="1280" alt="Screenshot 2024-02-23 232533" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/161089026/4a505b1b-dc91-4ec9-975e-a0276c6d0fd2">
**Please, provide a clear description what the bug is:**
I walk closer to a herb to loot it, and it disappear. I walk a bit back, and it reappear. Then walk closer again and it disappear

**Steps to reproduce the behavior with as much detail as possible:**

1. Find a herb.
2. Go towards it
3. See it disappear

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Happened earlier today with some of the elite mobs outside of razorfen downs. And tonight when trying to loot some herbs in Wetlands (stranglekelp and bruiseweed)

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**
It should allow me to loot them without them disappearing.
<img width="1280" alt="Screenshot 2024-02-23 233654" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/161089026/8f3f8e45-8712-4453-8fb4-b36d973f3933">
<img width="1280" alt="Screenshot 2024-02-23 233647" src="https://github.com/slowtorta/turtlewow-bug-tracker/assets/161089026/949442c1-d22c-42b3-b2eb-ff7a7a0490f3">

**Comment by Andersph123** [comment]
Also, just as extra bonus, it doesn't happen all the time, only sometimes

**Comment by 6556004** [comment]
![z](https://github.com/slowtorta/turtlewow-bug-tracker/assets/117788167/79e76ffd-8635-4e45-88a3-1beafe46ef51)
I will draw a picture to show it

The red line represents the edge and portal of the current map, which can be A ->B or B ->A

A+is the extended display area of A, because passing through the red line from A will transport you to B, so you will never appear in A+, B+is the same as A+

When you discover a purple star in A and walk towards it, you will pass through the red line, which is also the teleportation gate, and then you will appear in Zone B, so the star disappears. Because A and B are two zones, although they have the same name or look in the same place

**Comment by Andersph123** [comment]
So, what's the point? You saying it's intentional that it's 2 different zones inside the same zone?

**Comment by twowTurtReynolds** [comment]
Please read the pins. https://github.com/slowtorta/turtlewow-bug-tracker/issues/5312
