### ISSUE TITLE
圣骑大马任务物品没有给

### ISSUE THREAD

**Issue by crs1992** [slowtorta/turtlewow-bug-tracker#6370]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.人物在风暴烈酒角色叫  肾光保佑你
2. 任务完成没有给任务物品奥金马铠 后面任务没法完成。
3. 任务花了角色所有金币还没有钱删除任务重新完成

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by melg8** [comment]
I google translated it just for fun:

# No items were given in the Paladin Horse quest.

**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. The character in Stormstout is called Kidney Light Bless You
2. If the mission is completed and the mission item Arcane Horse Armor is not given, subsequent missions cannot be completed.
3. The task cost all the gold coins of the character and there is still no money. Delete the task and complete it again.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

**Comment by twowTurtReynolds** [comment]
The questline works fine.
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/91f24b36-7d30-44b4-9a30-d105583d125a)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/4051a92e-c624-4783-852f-77ec72a445d2)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/e4142821-25de-4a2e-a0ca-a4e8d80e7a05)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/b64e5e2b-a9c7-4b14-a10c-2bc56e1d79a6)

The item you need:
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/9bcdeb26-8cd9-46dd-a929-a93417ced757)
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/b84938f6-9cf2-4ddd-abcc-805dad75f77c)
