### ISSUE TITLE
Battleground Finder Puts Check Next To Wrong Battle Ground

### ISSUE THREAD

**Issue by MDGitHubRepo** [slowtorta/turtlewow-bug-tracker#687]
**Please, provide a clear description what the bug is:**
Selecting any bg besides warsong gulch always checks warsong gulch. See attached pics.

**Steps to reproduce the behavior with as much detail as possible:**

1. Select arathi to queue in Battleground Finder.
2. Review actual queued battleground mouseover and confirm arathi is queued.
![image](https://user-images.githubusercontent.com/28200369/147712348-8807888b-bb08-4a5d-8fb1-751f2d088f89.png)
3. Open Battleground Finder and note warsong gulch battle ground with check mark, making it now impossible to queue to that bg.
![image](https://user-images.githubusercontent.com/28200369/147712360-d6525441-9032-40bc-9385-fb8c0cb76468.png)

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
N/A

**Expected behavior. Describe how it should work:**
Selecting bg should queue for correct bg and then display check mark next to correct battle ground in finder window.

**Comment by MDGitHubRepo** [comment]
Additionally broken on second selection:
1. Queue to warsong in bg finder.
2. Mouseover bg queue to confirm what is queued, note warsong is queued.
3. Queue to blood ring in bg finder.
4. Mouseover bg queue to confirm warsong and blood ring are queued.
![image](https://user-images.githubusercontent.com/28200369/147712501-e5e0af24-f10f-42c5-ba7a-95ace9712482.png)
5. Open BG Finder menu and confirm check mark next to warsong and arathi.
![image](https://user-images.githubusercontent.com/28200369/147712493-3198bd7e-327f-4078-af0d-2194219448a0.png)

Should be check marks next to warsong and blood ring in this example.

**Comment by Rakura1** [comment]
Can confirm and in most cases you can also queue for the wrong BG.

**Comment by serranoble** [comment]
I would also add that there is no arathi option into my screen... I'm currently lvl 26, so I should be able to see it as part of the list but is not there... 😢

**Comment by pypaut** [comment]
Hello, I have this bug also.

**Steps to reproduce the behavior with as much detail as possible:**

1. Log on any character
2. Queue for any BG (for example, Warsong Gulch)
3. Log out from our character (go back to characters selection screen)
4. Log on another character
5. The BG you queued on your first character is "selected" and greyed out, cannot be selected.

To fix it, I had to log back to the first character and unqueue it.

I found a workaround:
1. From the second character (which is locked out from wanted queue), queue to any *other* BG
2. See the faction logo appear next to minimap, showing you are queued
3. Click the faction logo and unqueue
4. It is fixed and you can queue to the previously locked BG

**Expected behavior. Describe how it should work:**

I think a logged out character should automatically be unqueued.

**Comment by slowtorta** [comment]
Will be fixed in 1.16.1, thank you.
