### ISSUE TITLE
The Revantusk reputation weapons lost their models

### ISSUE THREAD

**Issue by Qix03** [slowtorta/turtlewow-bug-tracker#846]
When the expansion launched last year, the Revantusk and Silvermoon reputation vendors offered unique looking weapons at revered. However, at some point in the last few weeks, the Revantusk weapons have been replaced by extremely generic models instead of their intended troll themed ones.

**Comment by LeopoldHock** [comment]
Those models got changed intentionally due to the unique models being repurposed for other, future content. We're aware that the situation is far from ideal, but we simply lack unique troll-themed models right now. With luck, that will change sometime in the future and the models will then be a bit more unique again. 🙂
