### ISSUE TITLE
Character don't exit the game

### ISSUE THREAD

**Issue by IvenStill** [slowtorta/turtlewow-bug-tracker#926]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1.The character Iven had trouble exiting the game. He stayed in the game for a long time even after the logout. The last time he stayed in the game for 10 minutes after the Internet disconnect.
2. 
3. 

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

**Comment by slowtorta** [comment]
This is GM issue, not a bug tracker one. Request a manual .kick from a GM.

**Comment by IvenStill** [comment]
This is a bug, because it always happens, the GM is not able to help. GM sent me to this site.

**Comment by slowtorta** [comment]
Do you exit via logout option in the menu or via alt+F4?

**Comment by IvenStill** [comment]
I logged out in Stormwind and I was kicked out of the game because of the internet disconet once. The character remained in the game.

**Comment by Kruxis** [comment]
Greetings, 

usually you can't login again it's because the server takes a moment to understand that you lost your connection.
Depending on the situation this can even take minutes for the server to realise.

Please download the client again from https://turtle-wow.org/download and try that one. It is unusual that you get frequent DCs on logout. Might be some corrupted files.

I close this bug issue for now. If the problem persists after you tried what i said, please reply here and we can open the ticket again.

Safe travels!

**Comment by IvenStill** [comment]
Thanks for the help. I understood what the problem is. When an internet disconnect occurs, the character gets stuck in the game for a very long time (mb for 1 hour).
